### ISSUE TITLE
Add travel costs to the invoice

### ISSUE THREAD

**Issue by dskachan** [kevinpapst/kimai2#509] opened 2019-01-18 21:08 UTC
Hello Kevin. 
Just discovered your project - you did an amazing job!

I'm wondering whether it is possible to add some travel costs.... or maybe more general - some daily costs apart of time costs? I believe it is common, that if you need to make some job on the customer side - the customer will carry additional costs that will land in the invoice.

I believe that may be a very good feature that can increase a potential circle of users of your project!

I wish long life to the project,
-Dmitry

**Comment by kevinpapst** [comment] 2019-01-18 23:04
Hi Dmitry, thanks for your kind words and the feature request!
Yes, expenses are definitely planned for the future, but there are many other features waiting as well ;-) so I can't promise any timeline.

**Comment by kevinpapst** [comment] 2019-01-18 23:06
And there is already a feature request existing, so I will close this one and count yours as vote for the expenses feature.

Closing - duplicate of #351

**Closed by kevinpapst** 2019-01-18 23:06 UTC
Labels: duplicate
