### ISSUE TITLE
New entries: input field for rates

### ISSUE THREAD

**Issue by blochwitz** [kevinpapst/kimai2#610] opened 2019-03-01 07:47 UTC
Hi Kevin,

while creating a new time entry and putting a value into the input field for a hourly rate the system saves a wrong rate: it puts the value of the hourly rate also into the fixed rate field so the calculation is wrong. Deleting both entries doesn't fix it and deleting the value in the fixed rate field doesn't work.

We are using the latest version of Kimai2...

**Comment by kevinpapst** [comment] 2019-03-01 10:34
Tried it on the https://demo-v2.kimai.org where that doesn't seem to happen.
What exactly are you doing? Can you reproduce it in the demo?

**Comment by blochwitz** [comment] 2019-03-01 10:45
Hi Kevin,

i can't reproduce that in the demo cause the input fields for the rates are missing in the create view for a new entry (see below the screenshot). in my version (0.8.1.) two fields are displayed > „fixed rate“ and „hourly rate“...

i do the following:

1. i like to create a new entry by pressing plus or anywhere in the calendar view.
2. i select my time range, customer, project and activity and at the end i put a value in the hourly rate field.
3. i click save.
4. in the list view of all time entries i see the value of the hourly rate field incorrect (the calculation is not correct)
5. i click on the edit button to reedit the previously saved entry and than i can see my hourly rate value in the fixed rate input field.
6. i delete the value in the fixed rate input field
7. i click save.
8. nothing changed and the deleted value is still in the fixed rate input field.

![bildschirmfoto 2019-03-01 um 11 37 49](https://user-images.githubusercontent.com/42935152/53633280-546f3780-3c17-11e9-9b95-2c3b4ed03090.png)

**Comment by kevinpapst** [comment] 2019-03-01 13:35
For reproducing it in the demo, you have to use another account. The admin account can definitely edit the rates.

What happens if you create a new entry without adding an hourly rate (for the same activity/project combination)? Do you know that rates are inherited from the activity/project/customer? 
If one of those has a fixe rate, it will be used.

**Comment by blochwitz** [comment] 2019-03-01 17:39
Maybe I found the reason for the error:

for the entry i create i choose a project where we set a value for the hourly fix rate. and this value of the project is in the fixed rate input field (not in the hourly rate input field) after saving the entry. but it has to be in the hourly rate field... a fixed rate doesn't depend on the length of the entry.

**Comment by kevinpapst** [comment] 2019-03-01 17:47
> for the entry i create i choose a project where we set a value for the **hourly fix rate**

Hourly or fixed rate?

Could you please provide some screenshots for "edit project", "timesheet list" and "edit timesheet record", because I still cannot fully understand the problem.
Did you check https://www.kimai.org/documentation/timesheet.html#rate-calculation if the actual behavior is different from the documentation?

**Comment by blochwitz** [comment] 2019-03-02 00:05
„we set a value for the hourly“

**Comment by kevinpapst** [comment] 2019-03-02 01:59
I cannot reproduce the problem. Please re-test with an admin account if it is also happening in the demo.

**Comment by blochwitz** [comment] 2019-03-04 06:54
I can't reproduce that at the demo too.

At the demo i created a new project with a hourly rate
![bildschirmfoto 2019-03-04 um 07 39 22](https://user-images.githubusercontent.com/42935152/53715361-d77bd200-3e51-11e9-965c-87c5f791f289.png)

The same i made at our environment
![bildschirmfoto 2019-03-04 um 07 43 08](https://user-images.githubusercontent.com/42935152/53715407-01cd8f80-3e52-11e9-83c4-d1f72b3ec8c6.png)

After that i created a new time entry

at the demo:
![bildschirmfoto 2019-03-04 um 07 40 32](https://user-images.githubusercontent.com/42935152/53715439-1873e680-3e52-11e9-8d5c-db50cbbdb439.png)

and at our environment:
![bildschirmfoto 2019-03-04 um 07 43 55](https://user-images.githubusercontent.com/42935152/53715453-275a9900-3e52-11e9-9547-ccd27683b347.png)

At the demo the calculation is correct:
![bildschirmfoto 2019-03-04 um 07 50 50](https://user-images.githubusercontent.com/42935152/53715497-4527fe00-3e52-11e9-937a-bf5add9111f7.png)

at our environment not:
![bildschirmfoto 2019-03-04 um 07 44 15](https://user-images.githubusercontent.com/42935152/53715507-4c4f0c00-3e52-11e9-9819-cc1adc47323c.png)

**Comment by kevinpapst** [comment] 2019-03-04 12:28
Has the customer an hourly or fixes rate?
Has the activity an hourly or fixes rate?
What are your rounding and calculation configs? 
https://www.kimai.org/documentation/timesheet.html#rounding-of-begin-end-and-duration

**Comment by blochwitz** [comment] 2019-03-04 12:57
The customer has an hourly rate, the activity not and my rounding config is

```
        rounding:
            default:
                days: ['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
                begin: 5
                end: 5
                duration: 0
```

**Comment by kevinpapst** [comment] 2019-03-19 15:15
Still not reproducible for me. 
I am closing this if there is no more feedback.

**Closed** 2019-04-16 16:53 UTC
Labels: question
