### ISSUE TITLE
Fix headings on top of listings of teams, users, projects

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#2050] opened 2020-10-21 10:21 UTC
**Is your feature request related to a problem? Please describe.**
When scrolling in our large lists with 200 projects the header of the columns scrolls too.

**Describe the solution you'd like**
Fix the headings on top
or
create radio buttons with fixed rows to be displayed like 20 - 40 - 60 - all
or
not really good as a fast solution: a second header at the end of the page

**Comment by kevinpapst** [comment] 2020-10-21 12:47
Duplicate of #1443 - closing

**Closed by kevinpapst** 2020-10-21 12:47 UTC
Labels: duplicate
