### ISSUE TITLE
Very hard to export

### ISSUE THREAD

**Issue by yardstudio** [kevinpapst/kimai2#2345] opened 2021-02-13 18:12 UTC
**Describe the bug**
In My times is hard to set date over many than one year

**To Reproduce**
1. Go to '...'  My Times
2. Try set date from 2020 to 2021
3. In export will be availabvle only one year

**Logfile**
```
Add the last lines from your logfile at "var/log/prod.log" or "Doctor > Logs", around the time when the problem happened.
```

**Additional context**
 - Kimai version: 2 ?.?  (I have no idea where is version number in frontend vissible)
 - PHP version: 7.3
 - Device: [ Windows Desktop]
 - Browser [Chrome 85]

http://somup.com/crnIFXDDjE

**Comment by kevinpapst** [comment] 2021-02-13 19:43
Which Kimai version (check Doctor (in the title) or the About page (link in user dropdown).

Which locale/language do you use? See your user preferences.

**Comment by yardstudio** [comment] 2021-02-13 20:03
1.10 stable (Ayumi)

 

English

Timezone Europe Bratislava

**Comment by kevinpapst** [comment] 2021-02-13 20:07
Docker installation? 
Please upgrade to latest version 1.13. 
And in any case: the demo doesn't have the problem. Please give it a try yourself.

**Comment by yardstudio** [comment] 2021-02-13 20:09
No No,

live web usage :(

 

I am ftp mastodont, how can I simple update ?

**Comment by kevinpapst** [comment] 2021-02-14 17:02
Please try the demo and check if you can verify the bug there.

**Comment by kevinpapst** [comment] 2021-02-19 14:20
I am really sorry, FTP updates are not supported and that was always clearly communicated:
https://www.kimai.org/documentation/ftp.html#ftp-updates

I understand this is frustrating, sorry. 

I removed the support for FTP installations completely, because I simply don't have the time to create a working solution/installer. It is much easier if you get a simple hosting with SSH included. 

And regarding the bug: I am not able to reproduce it. If you find a way in the current demo version, please let me know how and I will fix it. But until then I am closing this as "cannot reproduce".

**Closed by kevinpapst** 2021-02-19 14:20 UTC
Labels: bug
