### ISSUE TITLE
Timesheets table empty after update

### ISSUE THREAD

**Issue by ralf1070** [kevinpapst/kimai2#878] opened 2019-06-25 13:07 UTC
**Describe the bug**
After updating from 0.9.0 to current master (7b95750dcf1d18930035586a66567939b91b969f) the KIMAI2_TIMESHEET table is empty.

**To Reproduce**
Start with lastest stable (0.9.0).
 
sqlite3_analyzer kimai2/var/data/kimai.sqlite

    *** Table KIMAI2_TIMESHEET and all its indices ********************************
    Percentage of total database......................  62.3%     
    Number of entries................................. 4332      

Execute:

    git pull origin master
    composer install --no-dev --optimize-autoloader
    bin/console cache:clear --env=prod
    bin/console cache:warmup --env=prod
    bin/console doctrine:migrations:migrate

After last step KIMAI2_TIMESHEET is empty:

    *** Table KIMAI2_TIMESHEET and all its indices ********************************
    Percentage of total database......................   5.3%    
    Number of entries................................. 0         

**Logfile**
Output of: bin/console doctrine:migrations:migrate

    Application Migrations                    
    
    WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
    Migrating up to 20190605171157 from 20190321181243
    
    ++ migrating 20190502161758
    
     -> ALTER TABLE kimai2_activities ADD COLUMN color VARCHAR(7) DEFAULT NULL
     -> ALTER TABLE kimai2_customers ADD COLUMN color VARCHAR(7) DEFAULT NULL
     -> ALTER TABLE kimai2_projects ADD COLUMN color VARCHAR(7) DEFAULT NULL
    
    ++ migrated (took 53.9ms, used 18M memory)
    
    ++ migrating 20190510205245
    
     -> CREATE TABLE kimai2_timesheet_tags (timesheet_id INTEGER NOT NULL, tag_id INTEGER NOT NULL, PRIMARY KEY(timesheet_id, tag_id))
     -> CREATE INDEX IDX_E3284EFEABDD46BE ON kimai2_timesheet_tags (timesheet_id)
     -> CREATE INDEX IDX_E3284EFEBAD26311 ON kimai2_timesheet_tags (tag_id)
     -> CREATE TABLE kimai2_tags (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(100) NOT NULL)
     -> CREATE UNIQUE INDEX UNIQ_27CAF54C5E237E06 ON kimai2_tags (name)
    
    ++ migrated (took 71.6ms, used 18M memory)
    
    ++ migrating 20190605171157
    
     -> ALTER TABLE kimai2_activities ADD COLUMN time_budget INTEGER DEFAULT 0 NOT NULL
     -> ALTER TABLE kimai2_activities ADD COLUMN budget DOUBLE PRECISION DEFAULT '0' NOT NULL
     -> ALTER TABLE kimai2_customers ADD COLUMN time_budget INTEGER DEFAULT 0 NOT NULL
     -> ALTER TABLE kimai2_customers ADD COLUMN budget DOUBLE PRECISION DEFAULT '0' NOT NULL
     -> DROP INDEX IDX_407F12069395C3F3
     -> CREATE TEMPORARY TABLE __temp__kimai2_projects AS SELECT id, customer_id, name, order_number, comment, visible, budget, fixed_rate, hourly_rate, color FROM kimai2_projects
     -> DROP TABLE kimai2_projects
     -> CREATE TABLE kimai2_projects (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, customer_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, order_number CLOB DEFAULT NULL COLLATE BINARY, comment CLOB DEFAULT NULL COLLATE BINARY, visible BOOLEAN NOT NULL, fixed_rate DOUBLE PRECISION DEFAULT NULL, hourly_rate DOUBLE PRECISION DEFAULT NULL, color VARCHAR(7) DEFAULT NULL COLLATE BINARY, budget DOUBLE PRECISION DEFAULT '0' NOT NULL, time_budget INTEGER DEFAULT 0 NOT NULL)
     -> INSERT INTO kimai2_projects (id, customer_id, name, order_number, comment, visible, budget, fixed_rate, hourly_rate, color) SELECT id, customer_id, name, order_number, comment, visible, budget, fixed_rate, hourly_rate, color FROM __temp__kimai2_projects
     -> DROP TABLE __temp__kimai2_projects
     -> CREATE INDEX IDX_407F12069395C3F3 ON kimai2_projects (customer_id)
    
    ++ migrated (took 107ms, used 18M memory)
    
    ------------------------
    
    ++ finished in 174.7ms
    ++ used 18M memory
    ++ 3 migrations executed
    ++ 19 sql queries

**Comment by kevinpapst** [comment] 2019-06-25 16:14
Oh shit! ... I hope you have a backup?!

I cannot verify this on my side. 
Maybe this has to do with the SQLIte compile time feature regarding foreign keys and the entries were deleted when the projects table was re-created. I don't have any other idea why that should happen.

If you have backup, could you please run each migration on its own to verify in which step it happens?
Use a copy of the backup for that and instead of the usual migration command do it step-wise `bin/console doctrine:migrations:migrate current+1`

**Comment by ralf1070** [comment] 2019-06-26 07:20
> Oh shit! ... I hope you have a backup?!

Sure - no problem.

> could you please run each migration on its own to verify in which step it happens?

Here it comes:
Step one: bin/console doctrine:migrations:migrate current+1

    Application Migrations                    
    WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
    Migrating up to 20190502161758 from 20190321181243
    ++ migrating 20190502161758
     -> ALTER TABLE kimai2_activities ADD COLUMN color VARCHAR(7) DEFAULT NULL
     -> ALTER TABLE kimai2_customers ADD COLUMN color VARCHAR(7) DEFAULT NULL
     -> ALTER TABLE kimai2_projects ADD COLUMN color VARCHAR(7) DEFAULT NULL
    ++ migrated (took 48.5ms, used 18M memory)
    ------------------------
    ++ finished in 86.6ms
    ++ used 18M memory
    ++ 1 migrations executed
    ++ 3 sql queries

Result:

    *** Table KIMAI2_TIMESHEET and all its indices ********************************
    Percentage of total database......................  62.3% 
    Number of entries................................. 4380      

Ok so far.

Step two: bin/console doctrine:migrations:migrate current+1

    Application Migrations                    
    WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
    Migrating up to 20190510205245 from 20190502161758
    ++ migrating 20190510205245
     -> CREATE TABLE kimai2_timesheet_tags (timesheet_id INTEGER NOT NULL, tag_id INTEGER NOT NULL, PRIMARY KEY(timesheet_id, tag_id))
     -> CREATE INDEX IDX_E3284EFEABDD46BE ON kimai2_timesheet_tags (timesheet_id)
     -> CREATE INDEX IDX_E3284EFEBAD26311 ON kimai2_timesheet_tags (tag_id)
     -> CREATE TABLE kimai2_tags (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(100) NOT NULL)
     -> CREATE UNIQUE INDEX UNIQ_27CAF54C5E237E06 ON kimai2_tags (name)
    ++ migrated (took 28.7ms, used 18M memory)
    ------------------------
    ++ finished in 57.7ms
    ++ used 18M memory
    ++ 1 migrations executed
    ++ 5 sql queries

Result:

    *** Table KIMAI2_TIMESHEET and all its indices ********************************
    Percentage of total database......................  57.3%    
    Number of entries................................. 4380      

Ok so far.

Step three: bin/console doctrine:migrations:migrate current+1

    Application Migrations                    
    WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
    Migrating up to 20190605171157 from 20190510205245
    ++ migrating 20190605171157
     -> ALTER TABLE kimai2_activities ADD COLUMN time_budget INTEGER DEFAULT 0 NOT NULL
     -> ALTER TABLE kimai2_activities ADD COLUMN budget DOUBLE PRECISION DEFAULT '0' NOT NULL
     -> ALTER TABLE kimai2_customers ADD COLUMN time_budget INTEGER DEFAULT 0 NOT NULL
     -> ALTER TABLE kimai2_customers ADD COLUMN budget DOUBLE PRECISION DEFAULT '0' NOT NULL
     -> DROP INDEX IDX_407F12069395C3F3
     -> CREATE TEMPORARY TABLE __temp__kimai2_projects AS SELECT id, customer_id, name, order_number, comment, visible, budget, fixed_rate, hourly_rate, color FROM kimai2_projects
     -> DROP TABLE kimai2_projects
     -> CREATE TABLE kimai2_projects (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, customer_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, order_number CLOB DEFAULT NULL COLLATE BINARY, comment CLOB DEFAULT NULL COLLATE BINARY, visible BOOLEAN NOT NULL, fixed_rate DOUBLE PRECISION DEFAULT NULL, hourly_rate DOUBLE PRECISION DEFAULT NULL, color VARCHAR(7) DEFAULT NULL COLLATE BINARY, budget DOUBLE PRECISION DEFAULT '0' NOT NULL, time_budget INTEGER DEFAULT 0 NOT NULL)
     -> INSERT INTO kimai2_projects (id, customer_id, name, order_number, comment, visible, budget, fixed_rate, hourly_rate, color) SELECT id, customer_id, name, order_number, comment, visible, budget, fixed_rate, hourly_rate, color FROM __temp__kimai2_projects
     -> DROP TABLE __temp__kimai2_projects
     -> CREATE INDEX IDX_407F12069395C3F3 ON kimai2_projects (customer_id)
    ++ migrated (took 49.3ms, used 18M memory)
    ------------------------
    ++ finished in 80.4ms
    ++ used 18M memory
    ++ 1 migrations executed
    ++ 11 sql queries

Result:

    *** Table KIMAI2_TIMESHEET and all its indices ********************************
    Percentage of total database......................   5.3%    
    Number of entries................................. 0         

Here the timesheet table is empty. Does this help you?

**Comment by ralf1070** [comment] 2019-06-26 07:31
Additional question: Initially I read that sqlite is not recommended for production use. As I - for whatever reason - don't like to use full fledged databases if not really needed, I decided to use sqlite anyway. It now seems to me sqlite is more in use for development tests then an activly supported database backend - is there a documented way to migrate kimai from sqlite to mariadb?

**Comment by kevinpapst** [comment] 2019-06-28 11:43
SQLite is conceptual not comparable to a full-fledged database, as it cannot guarantee foreign key constraints, alter table statemenets and a lot of other things. Yours seems to be compiled with foreign key support, but most installations are not.

It is great for some use-cases, but not for others. Kimai is one of the use-cases that cannot be fully supported. 

Migrating is straight forward: export all data from SQLite and import it in Mysql, then change the connection in your `.env` file.

**Comment by kevinpapst** [comment] 2019-06-28 12:22
Can I ask you for one more favor? It seems you are the only one who can test/reproduce this...

There is a database [connection listener](https://github.com/kevinpapst/kimai2/blob/master/src/Doctrine/SqliteSessionInitSubscriber.php#L38), which activates foreign key support for sqlite. Maybe this one causes the troubles on your end ... but just a wild guess.

Could you please try the upgrade again, after changing a method in your installation?

The [method preUp()](https://github.com/kevinpapst/kimai2/blob/master/src/Doctrine/AbstractMigration.php#L59) should be replaced with the following code to use the 3 new lines at the bottom:

```php
    public function preUp(Schema $schema): void
    {
        $this->abortIfPlatformNotSupported();

        if ($this->isPlatformSqlite()) {
            $this->connection->executeUpdate('PRAGMA foreign_keys = OFF;');
        }
    }

```

I am curious if it can fix your data loss issues.

**Comment by ralf1070** [comment] 2019-06-28 12:46
> Can I ask you for one more favor? It seems you are the only one who can test/reproduce this...

Sure no problem.

>     public function preUp(Schema $schema): void
> ```
> 
> I am curious if it can fix your data loss issues.

Done. But sorry - same result:

    *** Table KIMAI2_TIMESHEET and all its indices ********************************
    Percentage of total database......................   5.2%    
    Number of entries................................. 0

**Comment by ralf1070** [comment] 2019-06-28 12:52
> [SQLite ...] It is great for some use-cases, but not for others. Kimai is one of the use-cases that cannot be fully supported.

It's a kind of "religious" problem with me. Up to a point databases create more problems than they solve. Anyway - not your problem but mine ;)

> Migrating is straight forward: export all data from SQLite and import it in Mysql, then change the connection in your `.env` file.

I will give it a try.

**Comment by kevinpapst** [comment] 2019-06-28 13:09
Meeh... damned, then I honestly have no more idea what's going on and sadly cannot reproduce it. 

I do like the idea of SQLite very much, but the problem is that Kimai is evolving and the database structure is not "100% stable". Once this point is reached, SQLite is much safer to use. 
You can still migrate between both solutions and use SQLite in the future. 
But until then I really urge you to use MySQL to prevent such problems.

**Comment by ralf1070** [comment] 2019-06-28 13:47
Ok - as I'm not that much a database crack, I have some problems migrating. If you don'Ät like databases, they don't like you too. Fair enough.

What happend so far (dont laugh):

Dump sqlite:

    # sqlite3 var/data/kimai.sqlite 
    SQLite version 3.28.0 2019-04-16 19:49:53
    Enter ".help" for usage hints.
    sqlite> .output /tmp/kimai.sql
    sqlite> .dump
    sqlite> .exit

Create database:

    # mysql -p
    Enter password: 
    Welcome to the MariaDB monitor.  ...
    Server version: 10.2.22-MariaDB openSUSE package
    ...
    MariaDB [(none)]> create database kimai;
    Query OK, 1 row affected (0,00 sec)

As the exported SQL is a bit special I tried the python script found there: [https://stackoverflow.com/questions/18671/quick-easy-way-to-migrate-sqlite3-to-mysql](url):

    # python /tmp/dump_for_mysql.py < /tmp/kimai.sql > /tmp/kimai2.sql

Import SQL:

    # mysql -p kimai < /tmp/kimai2.sql 
    Enter password: 
    ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '--(DC2Type:datetime_immutable)
    , PRIMARY KEY(version))' at line 1
    

I tried out several other converter scripts but they failed too. It sounded a bit easier when you said it - short hint?

**Comment by kevinpapst** [comment] 2019-06-28 14:18
Have you tried https://dev.mysql.com/doc/workbench/en/wb-migration.html ?

Alternative: you can use Kimai to create the structure and then import only the data.

**Comment by ralf1070** [comment] 2019-06-28 14:51
Ah - good idea - will check it out next week.

**Comment by kevinpapst** [comment] 2019-06-30 00:40
I think I found a solution for the problem, so you can stay with SQLite. My changes prevent the foreign keys from being triggered, so the data in the timesheet table will not be deleted.

Instead of using master for the migration, please use the branch from this PR: 
https://github.com/kevinpapst/kimai2/pull/881

**Comment by kevinpapst** [comment] 2019-06-30 13:18
Can you please re-test with the latest master, I merged it as all my test were successful ... fingers crossed that I didn't miss anything ;-)

**Comment by ralf1070** [comment] 2019-07-01 07:28
I did an update and it seems to work like a charm - thank you very much.

**Comment by kevinpapst** [comment] 2019-07-01 11:58
Thats good to hear!
So both of us are happy: I learned new things about SQLite and you don't have to switch to MySQL. 🎉

**Closed by kevinpapst** 2019-07-01 11:58 UTC
Labels: bug, help wanted, upgrade

**Comment by ralf1070** [comment] 2019-07-01 12:33
:)
