### ISSUE TITLE
Wrong link in the CSS

### ISSUE THREAD

**Issue by Richigeht** [kevinpapst/kimai2#605] opened 2019-02-26 08:44 UTC
**Describe the bug**
I setup my kimai2 installation to run under: http://xxxxx./kimai2

If I access now the public folder, I cannot see the CSS Stylesheet:
           <link rel="stylesheet" href="/build/app.css?af8eca9aee27a459b31560560ceddb98">

This is the wrong link. The other elements, like register links etc. do work however correctly:

```
<link rel="shortcut icon" type="image/x-icon" href="/kimai2/public/favicon.ico">
--
  | <link rel="icon" type="image/x-icon" href="/kimai2/public/favicon.ico">
  | <link rel="icon" type="image/png" href="/kimai2/public/favicon-32x32.png" sizes="32x32">
  | <link rel="apple-touch-icon" href="/kimai2/public/apple-touch-icon.png">
  | <link rel="manifest" href="/kimai2/public/manifest.json">
  | <meta name="apple-mobile-web-app-title" content="Kimai 2">
  | <meta name="apple-mobile-web-app-capable" content="yes">
  | <meta name="mobile-web-app-capable" content="yes">
  | <meta name="application-name" content="Kimai 2">
  | <meta name="msapplication-config" content="/kimai2/public/browserconfig.xml">

```

**To Reproduce**
1. Setup to run Kimai in a subfolder on Apache2.
2. Start Kimai Website.

**Additional context**
 - Kimai version 0.8.3
 - PHP version 7.3

**Comment by hmr-it-jr** [comment] 2019-02-26 10:41
@Richigeht it's not a bug.

Check the requirements ([https://github.com/kevinpapst/kimai2#user-content-requirements](https://github.com/kevinpapst/kimai2#user-content-requirements)) 

> - Kimai needs its own sub-domain or you need to recompile the frontend assets for usage in a sub-directory

how to recompile frontend assets: [https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers.md](https://github.com/kevinpapst/kimai2/blob/master/var/docs/developers.md)

**Comment by Richigeht** [comment] 2019-02-26 13:29
Sorry for that then! Will do so. Thanks. 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by hmr-it-jr** [comment] 2019-02-26 14:38
You may want to close the issue then.

**Closed** 2019-02-26 15:14 UTC
