### ISSUE TITLE
Customer administration: search field

### ISSUE THREAD

**Issue by blochwitz** [kevinpapst/kimai2#667] opened 2019-03-29 09:46 UTC
Hi Kevin,

we added a lot of customers so in the administration view for customers we miss a search field to select customers faster.

![Bildschirmfoto 2019-03-29 um 10 45 08](https://user-images.githubusercontent.com/42935152/55224014-cd11e580-520f-11e9-91c7-8f94fa25097a.png)

**Comment by kevinpapst** [comment] 2019-03-29 14:43
Possible duplicate of #574
Free text search will be added for customer, project and activities at once.

**Comment by rarvin** [comment] 2019-05-09 18:19
Thanks for implementing this in 1.0. This really helps.

**Comment by kevinpapst** [comment] 2019-05-09 18:48
What?

**Comment by rarvin** [comment] 2019-05-09 18:53
Mistook this for the free text search you had implemented in 0.9 release for the Timesheet filter options. My apologies. I have deleted that comment.

**Comment by kevinpapst** [comment] 2019-05-09 18:57
Which "free text search field for Timesheet filter options" do you refer to? I am not sure that I know that one^^

**Comment by rarvin** [comment] 2019-05-09 18:59
https://www.kimai.org/documentation/theme.html
Searchable input types
The select boxes for customer, project and activity are by default the OS standard UI elements. This might be a limit for users with a long list of active and non-hidden elements.

Therefor a test is currently running, which can be activated setting the the following configuration:

kimai:
    theme:
        select_type: selectpicker
This will turn the select boxes into javascript elements with quick search option.

Why is this a beta test? It’s not clear, if we keep on using this javascript library or activate it by default. Therefor your feedback is highly welcome, please post your opinion at GitHub.
----
I am referring to the above one.

**Comment by blochwitz** [comment] 2019-05-13 07:21
Hi Kevin,

we are using the latest version 0.9 and activated the selectpicker config in local.yaml. but with that config the select boxes in the time entry creation view won't be displayed in version 0.9. In 0.8.1 all works fine with that config...

**Comment by kevinpapst** [comment] 2019-05-13 09:34
Thanks for the info, I remember having a problem there as well. Their JS state was not updated in the modals, but it is fixed in master.

**Closed** 2019-09-04 16:54 UTC
Labels: feature request, search

**Comment by kevinpapst** [comment] 2019-09-04 20:40
Search fields for all admin screens is now available in master
