### ISSUE TITLE
Improve calendar view with last activities

### ISSUE THREAD

**Issue by buoncri** [kevinpapst/kimai2#1852] opened 2020-07-29 06:53 UTC
**Is your feature request related to a problem? Please describe.**
The idea is to give more flexibility to calendar view for inserting data.

**Describe the solution you'd like**
Add a widget of "last activities" to drag and drop on calendar. 
Add a second widget to add to the previous widget other project/activities to enhance the graphical insert of data.

**Describe alternatives you've considered**
I think it has not alternatives.

**Additional context**
Here a screenshot of what i imagine

![Screenshot_2020-07-29 Taxi64](https://user-images.githubusercontent.com/3062441/88766416-46a94300-d178-11ea-8a46-db1391945755.png)

**Comment by HeinzWuert** [comment] 2020-07-29 07:20
Very very nice idea for e realy good workflow!
Two windows left of the calenar with the same size for projects and activities. After selcting project and setting mark the time in calandar.
But what's missing is the remark field. This is necessary for every booking. Have no idea how to implement, Maybe as a popup after setting the time in calendar?

**Comment by kevinpapst** [comment] 2020-08-01 20:53
See how it feels live in the AdminLTE demo: https://adminlte.io/themes/AdminLTE/pages/calendar.html
I would have already done that, but I am not convinced how that should work on mobile. Probably remove the draggable boxes altogether?

**Comment by buoncri** [comment] 2020-08-03 07:56
If i understand i think you are right, this can be a feature only for big screen, like pc, not phones.

**Comment by buoncri** [comment] 2020-08-06 06:56
I verified that don't actually work for mobile. It confuse dragging and scrolling.

**Comment by kevinpapst** [comment] 2020-09-10 07:23
@buoncri You already saw [the PR](https://github.com/kevinpapst/kimai2/pull/1962) :smile: and now you can test it at https://demo-branch.kimai.org/en/calendar/ with eg. `susan_super` / `kitten` and [other accounts](https://www.kimai.org/demo/)

**Comment by buoncri** [comment] 2020-09-10 08:10
Yesss ... i am going to test it immediatly :-D

**Comment by HeinzWuert** [comment] 2020-09-10 08:27
Should everything work?
If yes have a look on susan, week  Sep 7-13. Nothing can be editet anymore in calendar.
Deny overlapping times is activated!

**Comment by HeinzWuert** [comment] 2020-09-10 08:37
Select box: For me the project name shoult be always readable too.
First thing I would search is the project name
Second the matching activity

**Comment by buoncri** [comment] 2020-09-10 08:53
While testing (as superuser, susan_super) i notice that:

**What are OK** 
1) Colors (the same on widget bar and calendar timesheet entry)
2) Drag and drop from widget to calendar ... a dream came true 🥇 
3) Last activity records on the widget are giving more information tha the "Restart one of your last activities" button, as is possible to see the project and the customer

**What are not or can be changed**
1) exapandig the timesheet in calendar view ... it not save and give a "Validation Failed" error (i think can be linked to n°4)
2) the label of the widget is "Restart one of your last activities", if i can, i sugget to modify just to "Last activities" as the function is not the same of the start button
3) sometimes moving timesheets around calendar not saving the changes. (In details the timesheets of  'matrix-scalable-bandwith' activity of the demo)
4) timesheet editing after click on give a form error in start time (You already have an entry for this time)

**What i may humbly suggest**
1) the widget may be closed (and disappear) by a click on the upper right corner, as a window
2) add an option in settings/calendar to see or not the widget ? (not shure but may be for who don't want to use)

**What i have to say**
Thanks^3

**Comment by kevinpapst** [comment] 2020-09-10 10:49
There seems to be a problem when the "Allow overlapping times" config is deactivated. I activated it and at a first glance everything works as expected, most likely points 1,3 and 4 are linked to that problem @buoncri 

I will have a look into the error message: 
- should display more than just "Validation error" 
- and I will check what is wrong with the validation at all, as there is no parallel record existing at that time

I am trying to avoid adding more and more translations. But I know that the "Restart" wording is wrong here. I guess
that needs to be a new translation label, something like "add one of your latest activities to the calendar via drag & drop". Almost certain that (at least) some users don't understand that they can use drag&drop.

**Comment by kevinpapst** [comment] 2020-09-10 17:38
@HeinzWuert there was a bug (unrelated to this change) that prevented editing existing entries (in mode "Deny overlapping times") - which is fixed now.

@buoncri you can retry. I added better validation errors.

I would highly recommend that you do not deactivate "all overlapping times" while testing. This mode is currently not really compatible with the calendar for records, which are directly starting after another.
The problem is: you drop an entry for 13:00-13:30 and then want to drop one from 13:30-14:00. This is not allowed as they technically overlap for one second. Isn't very useful, but thats how it currently works. I will fix that, but not in this ticket (see #1963)

Demo is reinstalled.

**Comment by buoncri** [comment] 2020-09-11 07:08
While retesting

Now all is ok with moving and expanding timesheets.

**Closed** 2020-09-16 23:13 UTC
Labels: calendar, feature request

**Comment by radioactive76** [comment] 2020-11-09 16:39
I seem to have a problem when logging time, and then switching back to the calendar view with kimai2 1.11.1 that appears to be related to this feature. I have "allow overlapping times" disabled.

After logging times, the calendar view shows this:

![Kima_1 11 1_Calendar_Issue_20201109](https://user-images.githubusercontent.com/17219139/98569277-680ae680-22b2-11eb-81a2-4a747b433997.png)

The only way to fix it is to remove the offending time entry in the time log, this problem was not present in 1.10.2

**Comment by kevinpapst** [comment] 2020-11-09 16:47
You need to provide more information about the "offending timesheet".
I need exact details how to reproduce the issue. 

And please open a new issue this one is closed

**Comment by kevinpapst** [comment] 2021-02-14 10:30
@radioactive76 and everyone else reading here: this exact bug is caused by outdated JS and CSS assets. So if you are using docker, you have to upgrade your `public/` mount to use the latest assets as well.
