### ISSUE TITLE
Bulk insert daily working hours on a weekly/monthly basis by user

### ISSUE THREAD

**Issue by josefhuberfhcp** [kevinpapst/kimai2#2092] opened 2020-11-03 21:21 UTC
Hi,
I work for an IT consulting company and was ordered by my boss to do research into time tracking apps that are able to run on our shared-hosting environment, which essentially Kimai2 is the only relevant candidate for. My boss liked my demonstration of Kimai so far, but one feature seems to be missing that is crucial to him:

Our employes should not do their time tracking "live" on a daily basis, but rather once a week or once a month and only the duration on each day is relevant but not so much the starting and end time. Since it is quite tedious to repeat the time tracking steps 7 or 31 times, it would be awesome to have a bulk insert option  (e.g. getharvest has that)  for a given customer and project where for each day of the week (or month) there is an input field for the duration in the time tracking modal. The user can then just type in the duration on each day and saves all the times at once.
Is this a feature that is planned to be implemented? 
If not, could this be achieved with the "Custom-fields Plugin" or is it only possible to add info fields?

I also found the "Period insert Plugin" but it only seems to allow to enter the same duration for the whole period and no  individual working hour per day.
Also, in the Screenshot the plugin is listed in the "System" Menu. Does this mean that only the Administrator is able to do the bulk insert or are the regular employees also able to make use of it?

Thanks a lot and keep up the good work

**Comment by kevinpapst** [comment] 2020-11-03 22:08
You could probably use the drag & drop feature of the calendar and then stretch each task to the length of days duration.
Or your boss could sponsor the development of such a feature 👍 

For questions about the plugin, please contact the developer directly. You find the contact details in the store page.

**Comment by josefhuberfhcp** [comment] 2020-11-03 22:20
@kevinpapst Wow, that was fast, thank's a lot!
I will definitely have a look on the drag and drop feature approach, maybe that is good enough. Also i will adress my questions about the plugin to the responsible developer.
Since using e.g. getharvest involves monthly costs per user in _my_ opinion sponsoring would be an viable option, I just don't know yet what my boss thinks about that yet ;).
How would be the approach for sponsoring and what is the according cost range and development time when the feature is implemented for the public?

**Comment by kevinpapst** [comment] 2020-11-03 22:24
For customizations please contact me directly, you find my email eg here: https://www.kimai.org/store/custom-plugins.html

**Comment by marcseguin** [comment] 2020-11-04 16:44
May I contribute with the idea to inject a bulk of task items via the API from an excel file which can quickly prepared by the user. We did a similar approach with bulk insert of customer item and default projects per customer.

**Comment by kevinpapst** [comment] 2020-11-04 16:53
@marcseguin completely different topic: please post this in the task plugin repository

**Comment by marcseguin** [comment] 2020-11-05 11:48
> @marcseguin completely different topic: please post this in the task plugin repository

My fault as I used the term "task" - nevertheless the idea remains... perform a bulk insert of work items (=activities?) via the API.

**Comment by kevinpapst** [comment] 2020-11-05 12:14
Still completely different topic, as Web UI != API

And you can already create customer/projects/activities/timesheets via API, so I don't see what is missing. Please create a new issue for that.

**Comment by kevinpapst** [comment] 2020-11-08 02:58
Closing, duplicate of #312

**Closed by kevinpapst** 2020-11-08 02:58 UTC
Labels: feature request, plugin
