### ISSUE TITLE
Activities, Projects and Clients colors

### ISSUE THREAD

**Issue by racortesl** [kevinpapst/kimai2#2398] opened 2021-03-04 12:43 UTC
Hello there,

I don't know if this is a problem or not, but currently if the activity was assigned a custom color, when I change the project color, only change the color of the activities with default color, and I can't delete the assigned color, only assign one by one the activities color to match the project. The same happens with the client's color.

Should the project's color take precedence over activities, and the client's color over projects and activities?

**Comment by kevinpapst** [comment] 2021-03-04 14:03
true to: colors cannot be deleted. there are open feature requests to replace the browsers color chooser with something better (and with the option to delete an assigned color to revert back to default).

Duplicate of #1919.

Defined colors always win with activity over project over customer.

Closing, as there is nothing todo here. 
Questions can be posted here: https://github.com/kevinpapst/kimai2/discussions

**Closed by kevinpapst** 2021-03-04 14:03 UTC
Labels: wontfix
