### ISSUE TITLE
My times: total per day not correct when day is split over 2 pages

### ISSUE THREAD

**Issue by petervanhee** [kevinpapst/kimai2#2383] opened 2021-03-01 12:01 UTC
**Describe the bug**
When you have a day where time entries are split over 2 pages, than the total per day on page 2 does not take into account the time entries of that day on the first page. Also the total of the day on page 1 is not correct since it does not take into account the time entries of that day on the second page.

**To Reproduce**
Create time entries in order to have the case where time entries of the same date are split over 2 pages.

**Additional context**
 - Kimai version: 1.13
 - PHP version: ?.?
 - Device: Windows 10 on laptop
 - Browser Chrome 88.0.4324.190
![20210301_Page 2](https://user-images.githubusercontent.com/69186790/109494378-17e8a780-7a8e-11eb-879d-84158b2ab64c.png)
![20210301_Page 1](https://user-images.githubusercontent.com/69186790/109494379-18813e00-7a8e-11eb-8025-54b17d859828.png)

**Comment by kevinpapst** [comment] 2021-03-02 09:11
Yes, that's by design and won't be fixed in this listing view. At some point, I will create a new view, which puts all records of one day in one "box" while showing daily summaries. 

Until then: use reporting if you want the real daily numbers, or the dashboard or the user profile. 

This summary was never meant to be more than a quick glance at the numbers.

**Closed by kevinpapst** 2021-03-02 09:11 UTC
Labels: bug, wontfix
