### ISSUE TITLE
Possibility of viewing/adjusting user's timesheet in calendar view

### ISSUE THREAD

**Issue by cloggg** [kevinpapst/kimai2#3107] opened 2022-01-30 02:02 UTC
**Is your feature request related to a problem? Please describe.**
As a supervisor / HR employee, I am responsible for acceptance of user's timesheet. For the moment it is not easy task to look at the tasks of the users (tabelar view). It would be much practical to use Calendar view to see users tasks and to be able to adjust the 'crazy' records (running unfinished tasks, tasks which start ad midnight and end at midnight, etc...)

**Describe the solution you'd like**
The same story like for my own timesheet shown in calendar: I would like to be able to see calendar view of a certain person and be able to modify each task (as a teamleader or admin)

**Comment by kevinpapst** [comment] 2022-03-18 15:04
Closing as duplicate of #1067

**Closed by kevinpapst** 2022-03-18 15:04 UTC
Labels: duplicate, feature request, calendar

**Comment by kevinpapst** [comment] 2022-05-18 20:17
Added in #3314
