### ISSUE TITLE
Cannot login after Synology DSM update (critical error)

### ISSUE THREAD

**Issue by mauricebar** [kevinpapst/kimai2#1762] opened 2020-06-04 08:21 UTC
**Describe the bug**
The installation was working properly, I tried to import an old database from Kimai 0.9, which did not work because of the version. I started to load and create the customers, projects, users manually. After I finished the day I closed it and next day I got the "critical error" message. I though I created an error with my import trials (despite unsuccessful). I whipped the DB with the commands:
bin/console doctrine:schema:drop --force && \
bin/console doctrine:schema:create && \
After that I started again from zero and created some users and projects. Today as I want to log in I receive again the "critical error".

**To Reproduce**
1. Create a new user from scratch.
2. Create new users, projects, etc.
3. Log out.
4. Log in again.

**Logfile**
```
[prod after drop db 04-06.log](https://github.com/kevinpapst/kimai2/files/4728541/prod.after.drop.db.04-06.log)

```

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65902071/83732588-907c1e00-a64c-11ea-995b-ec3b12c652a1.png)

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:

    Device: Synology DS718+
    OS: DSM 6.2.2-24922 Update 4
    Browser Firefox 76.0.1 (64-Bit)

**Additional context**
 
    Kimai version 2
    PHP version 7.3
    -DB MariaDB v10
    -phpMyAdmin (PHP 5.6)

**Comment by mauricebar** [comment] 2020-06-04 08:56
I can create a new user and immediately access Kimai as this new user, but I cannot log in after I log out or with a different existing user once I log out.

**Comment by kevinpapst** [comment] 2020-06-04 12:56
Are you creating the user from the WebUI in the registration flow?
Please post the contents from var/log/prod.log (that is inside the Kimai directory)

**Comment by kevinpapst** [comment] 2020-06-04 12:57
BTW, you will run into update problems when using `bin/console doctrine:schema:create`.
Do NOT use this command. You can delete the database however you want, but you need to use `bin/console kimai:install` to create it!

**Comment by kevinpapst** [comment] 2020-06-04 15:22
The error is in the log, install libsodium (which handles the password encryption) or use a higher PHP version. Did you apply PHP 7.3 for Kimai?
Maybe the error comes from mixing different PHP version in bash (for importing data) and web.

**Comment by kevinpapst** [comment] 2020-06-04 16:00
The log says libsodium is not available

**Comment by buzter** [comment] 2020-06-04 22:20
@mauricebar Same constellation here. Using a DS718+ and from one day to another getting the critical error suddenly. My log says the same. Did You change sth on Your DS?
@kevinpapst Very sorry Kevin for misusing this place here as it seems to be a Synology DS problem.

**Comment by kevinpapst** [comment] 2020-06-04 22:52
Was a duplicate of #1764 

Check if libsodium is loaded: `php -i | grep "sodium"`
Activate the module: `sudo phpenmod sodium`

There is the Doctor screen in Kimai, check the PHP section and the entry "Modules", is there a `sodium` entry?

I guess the old password were cryptic with sodium and now these passwords cannot be resolved any longer. Please file a bug with Synology. 
Maybe you can install the PHP Sodium extension manually.

**Comment by buzter** [comment] 2020-06-05 05:11
As Maurice said, the registration of a new user works fine - at least if I don't have to confimate this user first. In this case the new user only has to press "Zur Startseite" after the registration process and is logged in. But after logging out the next login fails.

Sodium itself is (or at least seems to be) activated. Nevertheless I already opened a ticket with Synology yesterday but nothing really helpful from there until now.

**Comment by BeckeBauer** [comment] 2020-06-05 08:45
I face the same problem after updating the synology DSM yesterday. Sodium / libsodium seems to work
![Anmerkung 2020-06-05 104209](https://user-images.githubusercontent.com/51003649/83856247-87a54e00-a719-11ea-9665-00e5e373ccc7.jpg)
Any idea would be higly appreciated...

**Comment by kevinpapst** [comment] 2020-06-05 08:53
Are you sure that the web version of PHP is also 7.3? Check the Doctor screen!
You can test it by activating self-registration with confirmation email (create a new user and you are instantly logged in).

**Comment by BeckeBauer** [comment] 2020-06-05 09:00
the new user has no admin rights and the doctor screen is therefore not shown

**Comment by mauricebar** [comment] 2020-06-05 09:08
I opened a support case in Synology, too. I wait for a response.

**Comment by BeckeBauer** [comment] 2020-06-05 09:16
managed to solve it (temporarily). Changed the php version in the webstation from 7.3 to 7.2 and voila, it worked again...

**Comment by BeckeBauer** [comment] 2020-06-05 09:22
P.S. you can change it back to 7.3 and it still works

**Comment by kevinpapst** [comment] 2020-06-05 09:23
> the new user has no admin rights and the doctor screen is therefore not shown

Hah, right. But glad you found a workaround. Synology needs to jump in, I cannot do anything about it. But lets keep this issue open for now to track the problem for further users and possible solutions.

**Comment by buzter** [comment] 2020-06-05 10:37
@BeckeBauer Thx for the hint with php72. This worked for me too. But when I change back to php73 the critical error happens again!

**Comment by kevinpapst** [comment] 2020-06-05 10:45
Please check if the module is activated for PHP 7.3: 
https://www.synology.com/de-de/knowledgebase/DSM/help/WebStation/application_webserv_php

**Comment by BeckeBauer** [comment] 2020-06-05 16:54
It is quite strange, when I change back to php73, the sodium extension is deactivated by default

![Zwischenablage01](https://user-images.githubusercontent.com/51003649/83903188-fc9a7700-a75d-11ea-9bc4-5c4f1b3ef112.jpg)

If I leave it deactivated, I can log in 

![Zwischenablage02](https://user-images.githubusercontent.com/51003649/83903081-d1178c80-a75d-11ea-88fd-268f69abc3c5.jpg)
as soon as I activate the extension, log in fails again...

**Comment by kevinpapst** [comment] 2020-06-05 17:27
Did you have the same error in the log? What was your error message?

**Comment by buzter** [comment] 2020-06-11 12:17
@BeckeBauer @mauricebar Do You have news about this problem? Synology Support only tells me they need remote access to my NAS for troubleshooting. For security reason I can't and won't allow this. I know, my bad... For the next time I will keep up with the solution found by Beckebauer. Thx again for that.

I'll be thankful if You share new findings with me. Thx a lot in advance!

**Comment by BeckeBauer** [comment] 2020-06-11 12:56
No news so far, hope it will be solved with the next DSM update

**Comment by kevinpapst** [comment] 2020-06-11 22:59
After having a deeper look at the code I can only assume that the problem is the version of the libsodium header file.

The logfile from @mauricebar says that the error is triggered in this line:
https://github.com/symfony/security/blob/4.4/Core/Encoder/SodiumPasswordEncoder.php#L116

As it can reach this point in the code it means that Symfony detected a compatible sodium version before but can't find the function `sodium_crypto_pwhash_str_needs_rehash`.

This function was added in [libsodium 1.0.14](https://github.com/jedisct1/libsodium/releases/tag/1.0.14). So I assume that the DSM sodium extension was compiled against the wrong libsodium header file.

**Comment by kevinpapst** [comment] 2020-06-11 23:03
@buzter maybe you or someone else here can talk to the Synology support?

**Comment by mauricebar** [comment] 2020-06-12 07:48
> 
> 
> @BeckeBauer @mauricebar Do You have news about this problem? Synology Support only tells me they need remote access to my NAS for troubleshooting. For security reason I can't and won't allow this. I know, my bad... For the next time I will keep up with the solution found by Beckebauer. Thx again for that.
> 
> I'll be thankful if You share new findings with me. Thx a lot in advance!

No news from support. Actually to it happend that somehow by changing the PHP version my Web Admin interface was lost. I had CLI access but no "sudo" commands possible. It seems I break down something so in the end I had to do a RESET2 in the box. Now it is up again, I had to install the packages from the Packet center again and installed PHP7.2. 
It still does not work... To me it complains that it does not have rights to the folders (same as Kevin already pointed out to me) but I was sure I did. Now I have tested that when manually given (again) the folder permissions (chown, chmod commands) I get again the login screen, cannot log in, but can create a new user. After login out from the new user I receive again the critical error page. Then I have to set the folder permissions again to be able to see the login screen. Still I am not able to log in with an existing user.

**Comment by buzter** [comment] 2020-06-12 12:23
@kevinpapst Thank You so much for digging this deep in our problems. I contacted the Synology support with Your findings. Now it's waiting for an answer.

@mauricebar Sorry to hear that. For me the solution by BeckeBauer still works like charm. I stayed with php72 and did not change back to php73 after.

**Comment by buzter** [comment] 2020-06-15 14:59
Update: Synology support now ordered a system log. I sent them this morning.

**Comment by kevinpapst** [comment] 2020-07-19 12:54
Closing here, as I don't believe that this is a Kimai bug.
If someone receive an update from Synology, please post it here: might be important for all other sinology users!

**Closed by kevinpapst** 2020-07-19 12:54 UTC
Labels: question
