### ISSUE TITLE
Use export from command line

### ISSUE THREAD

**Issue by Jurgens92** [kevinpapst/kimai2#1646] opened 2020-04-17 06:23 UTC
Hi,

is there a way I can automate or script the exports, to email to certain people?
or is there a paid plugin for that?

thanks

**Comment by kevinpapst** [comment] 2020-04-18 12:59
Not yet. 
With 1.9 you can export invoices via Bash. 
But export is still an outstanding feature request.

**Comment by EliyahuEFGL** [comment] 2020-04-30 10:23
I would also like to see this feature.

**Comment by Jurgens92** [comment] 2020-10-06 07:09
Hi Kevin, thank you for considering this as a feature request, 
I just want to find out, if this has been rolled out?

thank you

**Comment by ozonorg** [comment] 2021-03-23 16:27
I just wanted to second the request for export to csv using bin/console on the command line.
This export would not need complex filtering but could just contain everything as it would be easy to process it subsequently using grep/sed etc.

**Comment by kevinpapst** [comment] 2021-03-23 16:29
Exporting to CSV shouldn't be a big problem using curl, no need to wait for that feature

**Comment by ozonorg** [comment] 2021-03-24 09:53
Thank you. It took me a while to find my way to api/doc.. So
 curl -X GET https://mydomain.test/api/timesheets  
will produce everything. I would still have to replace the ID numbers, so it is more than a one-liner ;)

**Comment by kevinpapst** [comment] 2022-06-24 22:46
Closing as duplicate of #1608
Please add your votes there.
Companies generating exports for their employees should consider to contact me for paid support.

**Closed by kevinpapst** 2022-06-24 22:46 UTC
Labels: feature request, export
