### ISSUE TITLE
Duplicate an Entry in Calendar view

### ISSUE THREAD

**Issue by MakhPeter** [kevinpapst/kimai2#1628] opened 2020-04-09 09:09 UTC
In calendar view, you can move entries to different dates by dragging them. I was wondering if you could add this feature where by pressing ctrl while dragging would make a copy/duplicate entry to another date. Thank you.

**Comment by kevinpapst** [comment] 2020-04-09 11:59
Nice idea! Don't know if and how easy that would be, but when I work at the calendar the next time, I will give it a try.

**Comment by buoncri** [comment] 2020-06-08 15:40
I'd like to explore this feature ... @kevinpapst can you direct me to the code where can i make a try ?

**Comment by kevinpapst** [comment] 2020-06-08 16:46
The calendar can be found here:
https://github.com/kevinpapst/kimai2/blob/master/templates/calendar/user.html.twig#L59

This is still an older version. I plan to update to the upcoming v5: 
https://fullcalendar.io/blog/2020/02/changes-in-the-upcoming-v5

So the current code needs to be rewritten. But nevertheless, please give it a try!

**Comment by buoncri** [comment] 2020-06-19 06:49
![immagine](https://user-images.githubusercontent.com/3062441/85104381-ca325480-b208-11ea-9cc0-5c4b03121e18.png)

Besides coping Entry, for the future development could be interesting to have 'last activities' somewhere in calendar view to drag and drop data, like in this demo of fullcalendar.

**Comment by mkemmler** [comment] 2020-08-30 12:23
Hello,

maybe you can make a copy when you are in the edit window, then you have a dupplicate entry what you can move...

thanks

**Comment by kevinpapst** [comment] 2022-06-24 22:51
With Drag & Drop support this issue might have become obsolete.

Anyways, please add your 👍 votes in  which would allow me to add custom actions (or the normal action menu from the timesheet listing) to calendar entries.

Record duplication would be there out of the box with a context menu, so I am closing this as duplicate of #2914

**Closed by kevinpapst** 2022-06-24 22:51 UTC
Labels: feature request, calendar
