### ISSUE TITLE
Custom-Fields Plugin - User Fields

### ISSUE THREAD

**Issue by MRIIOT** [kevinpapst/kimai2#1767] opened 2020-06-05 03:01 UTC
From reading the docs I see that 'Custom fields for users are not exported via the API'.  
I have a requirement to create users including their badge ID, phone number, etc via API.

Is this possible with this plugin or is there another method?

**Comment by kevinpapst** [comment] 2020-06-05 07:02
Duplicate of #1700 and #1602

**Closed by kevinpapst** 2020-06-05 07:02 UTC
Labels: API, duplicate
