### ISSUE TITLE
Team timesheet

### ISSUE THREAD

**Issue by lele89m** [kevinpapst/kimai2#1549] opened 2020-03-13 10:56 UTC
I would like to have a permission to view the teams timesheets, not only allowed to teamlead but to all the users in the teams. 
it is possible to add this feature?

**Comment by kevinpapst** [comment] 2020-03-13 11:04
Should already be possible. 
Read https://www.kimai.org/documentation/permissions.html
You need to change the permissions for Users

**Comment by lele89m** [comment] 2020-03-13 11:25
yes, but if i grant permission to a user of a team to view other timesheets nothing change. 
what is the correct permissione to set? 
i wish a team member(user) could see other team member timesheets..

**Comment by lele89m** [comment] 2020-03-13 11:26
p.s. Thank you very much for your quick response

**Comment by kevinpapst** [comment] 2020-03-13 17:00
Ah, that problem again. Sorry, I didn't read that you want normal users to see times of their colleagues.

This is not possible without workarounds, as this is a data privacy issue (at least in the EU).

You can add a workaround, which requires creating many teams. 
Create a new team for the user and set him as teamlead. Then add the users whose timesheets should be visible to that new team.

**Comment by kevinpapst** [comment] 2020-03-15 13:26
Duplicate of https://github.com/kevinpapst/kimai2/issues/1292 - closing

**Closed by kevinpapst** 2020-03-15 13:26 UTC
Labels: question
