### ISSUE TITLE
Theme color is showing navbar in white

### ISSUE THREAD

**Issue by julianhofmann** [kevinpapst/kimai2#2277] opened 2021-01-20 15:00 UTC
When choosing under "Display: colors" the option "black", the background-color changes to white. For all other colors ist changes to red, green and so on.

![Bildschirmfoto 2021-01-20 um 15 56 39](https://user-images.githubusercontent.com/25646388/105192564-873ab580-5b38-11eb-996c-5cfb9fe3ea5b.png)

**Comment by kevinpapst** [comment] 2021-01-20 15:06
Open the right toolbar by clicking the cogs icon in the upper right corner at: https://adminlte.io/themes/AdminLTE/
Try the theme switcher and you will see that this is not a bug, but works as expected... 
Even though you might expect something different.

If you want to change it, I do accept aPRs as it sounds reasonable.

You could add a new rule to overwrite the base theme in here:
https://github.com/kevinpapst/kimai2/blob/master/assets/sass/skins.scss

**Comment by HeinzWuert** [comment] 2021-01-20 18:57
Nice page!
Something for the wish list, Remark field in projects with real editor:
Bootstrap WYSIHTML5 Simple and fast

**Comment by kevinpapst** [comment] 2021-02-11 10:09
Closing as "works as expected" in a technical sense. As said: PRs to change that are welcome

**Closed by kevinpapst** 2021-02-11 10:09 UTC
Labels: wontfix
