### ISSUE TITLE
filter does not work

### ISSUE THREAD

**Issue by janfix12** [kevinpapst/kimai2#1809] opened 2020-07-08 09:39 UTC
**Describe the bug**
If I record time with the start button and want to measure it, then filtering by activity does not work.

**To Reproduce**
1. Go to 'Start time recording from the button on the dashboard'
2. choose the customer
3. select the project
4. here the activities are not shown, only globally available (here in the example "Free Support")
But if I now select free support and start the time tracking and then go to "My times" and edit the entry, I see that the filtering works.
I have migrated the data from version 1, the migration showed no errors.
The filtering also works for the customers and when I go to filter by activities, but not when I start a new time recording.

**Screenshots**
![Filter1](https://user-images.githubusercontent.com/66835560/86901628-2a802c00-c10d-11ea-971d-3fbde949666e.png)

![image](https://user-images.githubusercontent.com/66835560/86901870-79c65c80-c10d-11ea-8062-854d5e7573df.png)

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: Laptop
 - OS: Windows10
 - Browser: Chrome

**Additional context**
 - Kimai version 1.9 stable (Ayumi)
 - PHP version 7.4.4

**Comment by kevinpapst** [comment] 2020-07-08 09:41
Check your browsers javascript console and check the Kimai log file (doctor / Logs)

**Comment by janfix12** [comment] 2020-07-08 09:53
Hi Kevin,

in the console I see Error 400 with message: Bad Request

In the Log i see this error:

2020-07-07 15:18:03] request.ERROR: Uncaught PHP Exception FOS\RestBundle\Exception\InvalidParameterException: "Parameter "project" of value "%project%" violated a constraint "Parameter 'project' value, does not match requirements '\d+'"" at /opt/kimai/vendor/friendsofsymfony/rest-bundle/Exception/InvalidParameterException.php line 68 {"exception":"[object] (FOS\\RestBundle\\Exception\\InvalidParameterException(code: 0): Parameter \"project\" of value \"%project%\" violated a constraint \"Parameter 'project' value, does not match requirements '\\d+'\" at /opt/kimai/vendor/friendsofsymfony/rest-bundle/Exception/InvalidParameterException.php:68)"} []

**Comment by kevinpapst** [comment] 2020-07-08 21:52
Is that a reproducible behavior in your installation? 
Do you see it in the demo installation as well?

**Comment by janfix12** [comment] 2020-07-08 21:57
Yes I have installed the Version 1.18 and 1.19 fresh and then imported the v1 data with the usual way. And I tried once to upgrade from 1.18 to 1.19. The problem always occurred.
In the Kimai demo I cannot see this problem.

**Comment by kevinpapst** [comment] 2020-07-08 22:07
This is definitely not normal behavior, so we must find the reason.

So it is always happening for the create dialog and never with the edit dialog?

What is different between demo and your installation? 
Which tracking mode do you use?
Did you customize anything? Which configs did you change?

How many customers and projects do you have?
Does it happen with every customer/project?
What is the name of your projects (probably special characters used)?

Probably a browser plugin going nuts?

**Comment by janfix12** [comment] 2020-07-09 07:24
- Yes exactly only as soon as I start a new time recording the error comes, I want to edit this it works.

- One big difference i can see is actually only in the webinterface. i have dots that don't look well placed in the demo are these not in the word. Also in the demo, as soon as i select the customer, the filter is applied, i.e. only the projects of the customer are shown.

![image](https://user-images.githubusercontent.com/66835560/87009737-e2711000-c1c5-11ea-8645-046c0a7004c3.png)

- Standard mode
- actually only the ldap connection
- 11 customer and 28 projects
- I created a new customer with "test" and it didnt work, there are no special characters in the name of the customer
- I have also tried it in incognito mode with several browsers (Firefox, Chrome, Edge)

**Comment by kevinpapst** [comment] 2020-07-19 12:56
I have no clue whatsoever... can you give me access to your system so I can have a look myself?

**Comment by kevinpapst** [comment] 2020-07-23 12:27
No feedback, closing

**Comment by groovyrb** [comment] 2020-07-28 07:28
Hi @kevinpapst  I had a same issue in my Production env that in under construction,
Step to reproduce

- Create Timeshhet entry.
- Select Customer
- Select Project 
- Select Activity
- Select Task

Now Change the customer again now you will see all the entries you have selected does't change according to change happen in above fields. there is no option for refresh so we have to close and restart the same process to add timesheet entry to a specific activity and task

**Comment by kevinpapst** [comment] 2020-07-28 10:12
Seems there are multiple users who have the issue. @janfix12 @buoncri a 👍 is good to signal that, but as I can only fix what I can see, so some input to allow me to reproduce it would be appreciated!

@groovyrb what do you mean with "Select task"? Are you talking about the "create timesheet" screen?
Everything seems to be working on my end, so I need more details. Is there a related error in your javascript console?

@janfix12 mentioned the log file error regarding the `%project%` parameter in the API - that is a strong indication, that the [javascript has a problem](https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiSelectDataAPI.js#L77). The parameter `%project%` should be replaced at least with an empty string. Seems it isn't and I have no clue why/how that could be.

I am literally blind and cannot fix what I cannot reproduce.

**Comment by groovyrb** [comment] 2020-07-28 10:28
@kevinpapst  what do you mean with "Select task"? Are you talking about the "create timesheet" screen?
This is new field which I have added according to my software requirement.
If you want I can create a user for you and will share you in personal so you can check why activity are not coming after first time change in customer.

**Comment by kevinpapst** [comment] 2020-07-28 10:29
Yes please! I hope I can identify the problem in your system. You know my email :)

**Comment by kevinpapst** [comment] 2020-07-28 11:46
@groovyrb your issue comes from changing the API result structure. Check this JS component: https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiSelectDataAPI.js#L77 which needs to be adapted to work with the new structure.

I am closing here again, as I cannot reproduce the issue with a clean Kimai installation.
Any input is welcome and I will reopen if someone has more infos.

**Comment by groovyrb** [comment] 2020-07-28 11:58
Thanks for your valuable time will look into this. thank you so much

**Comment by kevinpapst** [comment] 2020-07-28 12:00
Wrong line linked. Check that call: https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiSelectDataAPI.js#L65
and from there on where the "data" object is used. It needs to be updated to use your result structure.

**Comment by kevinpapst** [comment] 2020-08-16 13:59
So I found one/two bugs in the javascript, both related to the same problem:

- select a project with activities and then select a customer that has no project
- maybe the same happens when no global activity is existing and a project without activity is selected (not sure about that one)

See #1894 for the changes.

I will merge them and you could please update your installation and check if anything changed @janfix12 ?

**Closed** 2020-08-16 14:20 UTC
Labels: waiting for feedback
