### ISSUE TITLE
Allow users to create activities

### ISSUE THREAD

**Issue by jj1024** [kevinpapst/kimai2#2404] opened 2021-03-06 23:23 UTC
**Describe the solution you'd like**

I think it would be useful if when a user searches for an activity or project when starting a timer, they were able to create a new activity or project if the correct one doesn't already exist right from the new timer menu.

**Comment by HeinzWuert** [comment] 2021-03-07 13:23
If something like this can be done for individual cases by role settings ok, otherwise never ever!
Normaly this must be under control of the admins to avoid wild growth!

**Comment by kevinpapst** [comment] 2021-03-07 13:30
This is a typical "freelancer" feature requests, when Kimai is used by only 1 or 2 people.
I think its legit to simply re-use the existing `create_activity` permission and open a modal to create an activity (in theory).

But in practice, I am not convinced as well (low priority) and this is a duplicate of #621. Please vote there, as I am closing this one.

**Closed by kevinpapst** 2021-03-07 13:30 UTC
Labels: duplicate
