### ISSUE TITLE
Invoice - Print and preview results are not the same when no users are selected 

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#1114] opened 2019-09-16 14:43 UTC
**Describe the bug**
The print results displayed in the invoice view and the preview results shown are not the same. The print view results seems accurate.

Options used for the invoice export are invoice document - timesheet; sum calculation: user (one entry per user)

**To Reproduce**
1. Go to invoice, choose the customer, trigger an invoice  
2. Click on Preview
3. See the values shown in the said view; click on print and see the report generated and compare the values the values dont match.

Even when a project is chosen the results are not the same between views. But when the activity was also additionally chosen the results matched.

Additionally the issue seems to be present only when no users are chosen. If one were to choose a customer and a said user and run the invoice the results between print and preview are the same. I have tried with multiple users also and the results are the same. Issue seems to be present when no users are selected. 

Same issue is present with the javascript option on and off, so this is not causing the issue.

**Screenshots**
Unable to share screen shots since it contains customer data.

**Comment by infeeeee** [comment] 2019-09-16 20:31
If you hover your mouse over the preview button it shows 'Limited to 500 entries':
![image](https://user-images.githubusercontent.com/1271737/64990977-39bd9100-d8d1-11e9-962b-99e0e95856cc.png)

> Issue seems to be present when no users are selected.

It only happens when there are more than 500 entries. If less than 500 you will see the same

I think this intended to work this way, it's a feature not a bug :)

**Comment by rarvin** [comment] 2019-09-17 03:22
There are only 120 users in the system and the option chosen is one record
per user so it should be within the 500 limit and should display the same
sim in the preview and print.
-- 
Regards,
Aravind

**Comment by kevinpapst** [comment] 2019-09-17 09:24
One entry per user actually does not mean it renders one entry per user, it means it renders one entry per hourly/fixed rate per user. So you could have actually generated multiple entries per user.

But I guess the real reason is: 
- Not the merged end result is currently limited, but the initial data.
- That means: the query is limited to 500 results, 500 entries are fetched from the database and then merged. 

I guess thats the case here, but I can't confirm as I don't know how many records were filtered.

**Comment by rarvin** [comment] 2019-09-17 10:05
Can we have this limit configurable so that someone who wants to see the
whole set can vary it as needed.

Also there was never any delay in displaying results with the invoice page
the only problems were with the export page as it started with a default
setting for time as a months worth of interval.

Currently we can see the results in the report but one has to scroll down a
lot to see the results the summation in the preview page was quiet helpful
earlier for quick viewing of details.
-- 
Regards,
Aravind

**Comment by kevinpapst** [comment] 2019-09-18 15:40
You can change the value here: 
https://github.com/kevinpapst/kimai2/blob/master/src/Controller/InvoiceController.php#L71

I will think about how that can be handled better. 
Maybe limiting this should be removed altogether as it produces invalid results. 
I just didn't test with such an amount of records.

**Comment by rarvin** [comment] 2019-09-19 15:04
I have changed it to 10000 and now I get the same results when I open a
days data. I think this should be enough for now.

**Comment by kevinpapst** [comment] 2019-09-19 15:05
Thanks for the confirmation, then I remove that functionality from invoice.

**Comment by rarvin** [comment] 2019-09-20 13:02
@kevinpapst kindly do not remove the invoice preview functionality altogether I am happy changing the value and seeing the results. If you remove it completely you could take away a very critical functionality that I tend to use all the time. I request you to please retain it. Maybe remove it for general users and provide this as a toggle which users like me could enable and use. This is a sincere request.

**Comment by kevinpapst** [comment] 2019-09-20 13:03
I just remove the limitation to 500 results, so the bug will be gone. The preview will definitely stay!

**Comment by rarvin** [comment] 2019-09-20 13:09
@kevinpapst Thank you.

**Closed** 2019-09-20 14:00 UTC
Labels: bug
