### ISSUE TITLE
Show coloured dots and description of activties in timesheet edit dialog

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1763] opened 2020-06-04 08:30 UTC
Colored dots can be assigned to each setting in the Settings menu.
Is it possible to display them in the selection menu when entering times?
As already noted earlier, the explanation field for the settings is well-meant, but completely useless if it is not displayed as a popup for the user when "mouse over".

**Comment by kevinpapst** [comment] 2021-03-19 14:18
Closing as duplicate of #1882

**Closed by kevinpapst** 2021-03-19 14:18 UTC
Labels: duplicate, feature request
