### ISSUE TITLE
Search results differ onscreen, export shows fewer records than what is on screen

### ISSUE THREAD

**Issue by seanvl** [kevinpapst/kimai2#2094] opened 2020-11-06 04:30 UTC
**Describe the bug**
Depending on which user is logged in (both administrators by role) out put of issues differs. I originally discovered this issue when trying to create invoices and not being able to match the numbers up, so I know that it is not just the excel output. These records were all imported. This problem is highlighted with this one user but it occurs with other users too.
[Kimai Search Bug.xlsx](https://github.com/kevinpapst/kimai2/files/5499081/Kimai.Search.Bug.xlsx)

Please review the attached spreadsheet
**Tab 1 Search 10.27 Sean Search** - One entry for 8/27 however if you look at the screenshot on the tab there are 2 entries that were found, only 1 was exported.
**Tab 1 Search 10.27-10/28 Sean Search** - Searched for 8/27 -8/28. This time the export produces both entries on 8/27

**To Reproduce**
1. Login as user1 (happens to be 'sean' on my system) with admin
[Kimai Search Bug.xlsx](https://github.com/kevinpapst/kimai2/files/5499072/Kimai.Search.Bug.xlsx)

 privileges 
2. Click on 'Timesheets' in the Administration section of the navigation panel
3. in Search search for user1 (happens to be 'sean' on my system) date should only be 8/27/2020, do not close the window
4. Export to Excel
5. in Search search for user1 (happens to be 'sean' on my system) on 8/27/2020 - 8/28/2020, do mot close the window
6. Export to Excel

**Logfile**
```
[2020-11-04 23:58:45] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2020-11-04 23:58:45] app.CRITICAL: Invoice "2020-003-collinear_group-cgsow1.pdf" already exists [] []
[2020-11-04 23:58:45] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2020-11-04 23:58:45] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2020-11-04 23:58:45] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"secured_area","authenticators":1} []
[2020-11-04 23:58:45] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Component\\Security\\Core\\User\\ChainUserProvider","username":"andrew"} []
[2020-11-04 23:58:45] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2020-11-04 23:58:45] request.INFO: Matched route "invoice". {"route":"invoice","route_parameters":{"_route":"invoice","_controller":"App\\Controller\\InvoiceController::indexAction","_locale":"en"},"request_uri":"https://time.xylariam.com/en/invoice/?create=&customer=1&daterange=2020-09-25%20-%202020-10-29&exported=1&projects%5B0%5D=3&searchTerm=&tags=&template=1","method":"GET"} []
[2020-11-04 23:57:32] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2020-11-04 23:57:32] app.CRITICAL: Invoice "2020-003-collinear_group-cgsow1.pdf" already exists [] []
[2020-11-04 23:57:32] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2020-11-04 23:57:32] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2020-11-04 23:57:32] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"secured_area","authenticators":1} []
[2020-11-04 23:57:32] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Component\\Security\\Core\\User\\ChainUserProvider","username":"andrew"} []
[2020-11-04 23:57:32] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2020-11-04 23:57:32] request.INFO: Matched route "invoice". {"route":"invoice","route_parameters":{"_route":"invoice","_controller":"App\\Controller\\InvoiceController::indexAction","_locale":"en"},"request_uri":"https://time.xylariam.com/en/invoice/?activities%5B0%5D=7&activities%5B1%5D=6&activities%5B2%5D=4&activities%5B3%5D=5&create=&customer=1&daterange=2020-09-25%20-%202020-10-29&exported=1&markAsExported=1&projects%5B0%5D=3&searchTerm=&tags=&template=1","method":"GET"} []
[2020-11-04 23:54:38] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2020-11-04 23:54:38] app.CRITICAL: Invoice "2020-003-collinear_group-cgsow1.pdf" already exists [] []
[2020-11-04 23:54:38] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2020-11-04 23:54:38] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2020-11-04 23:54:38] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"secured_area","authenticators":1} []
[2020-11-04 23:54:38] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Component\\Security\\Core\\User\\ChainUserProvider","username":"andrew"} []
[2020-11-04 23:54:38] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2020-11-04 23:54:38] request.INFO: Matched route "invoice". {"route":"invoice","route_parameters":{"_route":"invoice","_controller":"App\\Controller\\InvoiceController::indexAction","_locale":"en"},"request_uri":"https://time.xylariam.com/en/invoice/?activities%5B0%5D=7&activities%5B1%5D=6&activities%5B2%5D=4&activities%5B3%5D=5&create=&customer=1&daterange=2020-09-25%20-%202020-10-29&exported=5&markAsExported=1&projects%5B0%5D=3&searchTerm=&tags=&template=1","method":"GET"} []
[2020-11-04 19:16:13] request.CRITICAL: Uncaught PHP Exception RuntimeException: "There is no user provider for user "Proxies\__CG__\App\Entity\User". Shouldn't the "supportsClass()" method of your user provider return true for this classname?" at /var/www/kimai2/vendor/symfony/security-http/Firewall/ContextListener.php line 295 {"exception":"[object] (RuntimeException(code: 0): There is no user provider for user \"Proxies\\__CG__\\App\\Entity\\User\". Shouldn't the \"supportsClass()\" method of your user provider return true for this classname? at /var/www/kimai2/vendor/symfony/security-http/Firewall/ContextListener.php:295)"} []
[2020-11-04 19:16:13] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\SwitchUserToken"} []
[2020-11-04 19:16:13] request.INFO: Matched route "timesheet". {"route":"timesheet","route_parameters":{"_route":"timesheet","page":1,"_controller":"App\\Controller\\TimesheetController::indexAction","_locale":"en"},"request_uri":"https://time.xylariam.com/en/timesheet/","method":"GET"} []
[2020-11-04 18:59:35] console.DEBUG: Command "list 'doctrine:schema:validate' --env=prod" exited with code "1" {"command":"list 'doctrine:schema:validate' --env=prod","code":1} []
[2020-11-04 18:59:35] console.ERROR: Error thrown while running command "list 'doctrine:schema:validate' --env=prod". Message: "There are no commands defined in the "doctrine:schema:validate" namespace.  Did you mean this?     doctrine:schema" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"doctrine:schema:validate\" namespace.\n\nDid you mean this?\n    doctrine:schema at /var/www/kimai2/vendor/symfony/console/Application.php:597)","command":"list 'doctrine:schema:validate' --env=prod","message":"There are no commands defined in the \"doctrine:schema:validate\" namespace.\n\nDid you mean this?\n    doctrine:schema"} []
[2020-11-04 18:53:53] console.DEBUG: Command "list 'doctrine:schema:validate' --env=prod" exited with code "1" {"command":"list 'doctrine:schema:validate' --env=prod","code":1} []
[2020-11-04 18:53:53] console.ERROR: Error thrown while running command "list 'doctrine:schema:validate' --env=prod". Message: "There are no commands defined in the "doctrine:schema:validate" namespace.  Did you mean this?     doctrine:schema" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"doctrine:schema:validate\" namespace.\n\nDid you mean this?\n    doctrine:schema at /var/www/kimai2/vendor/symfony/console/Application.php:597)","command":"list 'doctrine:schema:validate' --env=prod","message":"There are no commands defined in the \"doctrine:schema:validate\" namespace.\n\nDid you mean this?\n    doctrine:schema"} []
[2020-11-04 18:53:12] console.DEBUG: Command "list 'doctrine:schema:validate'" exited with code "1" {"command":"list 'doctrine:schema:validate'","code":1} []
[2020-11-04 18:53:12] console.ERROR: Error thrown while running command "list 'doctrine:schema:validate'". Message: "There are no commands defined in the "doctrine:schema:validate" namespace.  Did you mean this?     doctrine:schema" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"doctrine:schema:validate\" namespace.\n\nDid you mean this?\n    doctrine:schema at /var/www/kimai2/vendor/symfony/console/Application.php:597)","command":"list 'doctrine:schema:validate'","message":"There are no commands defined in the \"doctrine:schema:validate\" namespace.\n\nDid you mean this?\n    doctrine:schema"} []
[2020-11-04 18:51:24] console.DEBUG: Command "--v" exited with code "1" {"command":"--v","code":1} []
[2020-11-04 18:51:24] console.ERROR: Error thrown while running command "--v". Message: "The "--v" option does not exist." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"--v\" option does not exist. at /var/www/kimai2/vendor/symfony/console/Input/ArgvInput.php:203)","command":"--v","message":"The \"--v\" option does not exist."} []
[2020-11-04 18:36:51] request.CRITICAL: Uncaught PHP Exception RuntimeException: "There is no user provider for user "Proxies\__CG__\App\Entity\User". Shouldn't the "supportsClass()" method of your user provider return true for this classname?" at /var/www/kimai2/vendor/symfony/security-http/Firewall/ContextListener.php line 295 {"exception":"[object] (RuntimeException(code: 0): There is no user provider for user \"Proxies\\__CG__\\App\\Entity\\User\". Shouldn't the \"supportsClass()\" method of your user provider return true for this classname? at /var/www/kimai2/vendor/symfony/security-http/Firewall/ContextListener.php:295)"} []
[2020-11-04 18:36:51] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\SwitchUserToken"} []
[2020-11-04 18:36:51] request.INFO: Matched route "dashboard". {"route":"dashboard","route_parameters":{"_route":"dashboard","_controller":"App\\Controller\\DashboardController::indexAction","_locale":"en"},"request_uri":"https://time.xylariam.com/en/dashboard/","method":"GET"} []
[2020-11-04 16:26:24] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2020-11-04 16:26:24] request.CRITICAL: Uncaught PHP Exception App\Validator\ValidationFailedException: "Validation Failed" at /var/www/kimai2/src/Timesheet/TimesheetService.php line 254 {"exception":"[object] (App\\Validator\\ValidationFailedException(code: 400): Validation Failed at /var/www/kimai2/src/Timesheet/TimesheetService.php:254)"} []
[2020-11-04 16:26:24] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2020-11-04 16:26:24] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
[2020-11-04 16:26:24] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"secured_area","authenticators":1} []
[2020-11-04 16:26:24] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Component\\Security\\Core\\User\\ChainUserProvider","username":"sean"} []
[2020-11-04 16:26:24] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2020-11-04 16:26:24] request.INFO: Matched route "duplicate_timesheet". {"route":"duplicate_timesheet","route_parameters":{"_route":"duplicate_timesheet","_controller":"App\\API\\TimesheetController::duplicateAction","_format":"json","id":"385"},"request_uri":"https://time.xylariam.com/api/timesheets/385/duplicate","method":"PATCH"} []
[2020-10-31 00:02:04] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []```

**Additional context**
 - Kimai version:  1.11.1
 - PHP version: 7.2.24-0ubuntu0.18.04.7
--
 - Device: Linux time.xylariam.com 5.4.0-1029-aws #30~18.04.1-Ubuntu SMP Tue Oct 20 11:09:25 UTC 2020 x86_64
 - Browser Chrome Linux Version 86.0.4240.183 (Official Build) (64-bit)

**Comment by kevinpapst** [comment] 2020-11-06 15:38
Please provide screenshots (not in excel) and the exports of these exact rows from the database.
Otherwise I cannot help finding the root cause of the issue.

**Comment by kevinpapst** [comment] 2020-11-13 10:43
No feedback, closing

**Closed by kevinpapst** 2020-11-13 10:43 UTC
Labels: bug, waiting for feedback
