### ISSUE TITLE
Export reporting wrong durations vs. Print

### ISSUE THREAD

**Issue by randomev** [kevinpapst/kimai2#1496] opened 2020-02-25 07:29 UTC
**Describe the bug**
I have 4 time entries. In Export Preview they show wrong duration, each is shown as 1 h. 
I can see correct durations when I click Print at Export screen. Correct durations are 2:30h, 1:00h, 1:00h and 6:30h.

**Screenshots**
Export - preview - how export shows hours - notice 1 hour in each.
Print-preview - how print shows - correct hours
Database - how things are at database-level, hopefully helpful to reproduce with this data

Kimai version 1.7

<img width="670" alt="Database" src="https://user-images.githubusercontent.com/541276/75224591-6e534400-57b1-11ea-8f27-25becc910371.png">
<img width="1507" alt="Print-preview" src="https://user-images.githubusercontent.com/541276/75224599-714e3480-57b1-11ea-9a78-5f6d35cd87aa.png">
<img width="1299" alt="Export-preview" src="https://user-images.githubusercontent.com/541276/75224606-74492500-57b1-11ea-9282-6adfd9e4e9bf.png">

**Comment by kevinpapst** [comment] 2020-02-25 09:08
Thanks. Maybe already fixed for 1.8? Can't reproduce it with master.

**Comment by kevinpapst** [comment] 2020-03-15 13:13
Fixing bugs that can't be reproduced is impossible without feedback => closing.

**Comment by randomev** [comment] 2020-04-01 10:20
Reason not responding earlier is that we were waiting suitable time-slot for us to update to 1.8. Now I had time to check this after we updated to 1.8. Same issue with these same timesheets, duration shows as "1" in every row in export. In fact, with this project, it seems that every row is reported as "1", eg. wrong format altogether. As opposed to another project, duration in export screen is formatted as 01:00 h or 01:30 h. Hope this helps to find the issue. Also correct time is reported at Project-page under Budget. 

Looked at html of page, for few rows:

<td class=" text-nowrap" data-duration="10800">
                        1
                    </td> 

and another row 

<td class=" text-nowrap" data-duration="9000">
                        1
                    </td>

and yet another:

<td class=" text-nowrap" data-duration="3600">
                        1
                    </td>

So number does not correspond to data-duration. As opposed with working project, it seems to be

<td class=" text-nowrap" data-duration="21600">
                        06:00 h
                    </td>

so data-duration seems to equal 10 second time (60*60*6) which seems more reasonable.

**Comment by kevinpapst** [comment] 2020-04-01 13:42
Please check if these entries are fixed rate entries:
https://github.com/kevinpapst/kimai2/blob/master/templates/export/index.html.twig#L94

**Comment by randomev** [comment] 2020-04-02 07:39
Yes they are. Only fixed-rate entries in the whole database. Thank you for pointing this out. Duration is shown correctly after I removed fixed rate from these entries. I don't know where that "fixed-rate" came from, possibly from budget as this was first project where we tried pre-determined budget. Most likely user error in our end.

By the way, duration as shown as "1" for fixed-rate entries, that's something I did not expect as a user. Would expect that duration and price are 2 different things if fixed-rate is used. So for fixed rate entries duration is shown as normal and only the price is calculated with 1 x fixed rate when needed, not the duration.

Example use case - we have job-type of "small, max 1/2 day job" agreed with clients so these jobs cost always 100 usd per job. So fixed rate is great for that. But every month I would like to see how long in average it has taken to make these jobs in previous month so is it a good business model or not for us. So I would like to see total hours for these types and compare this to price paid. It's already possible, I can export data and see from there so thats's ok and would work nicely. Only thing that was inconsistent was that export screen that showed duration as 1.

<img width="938" alt="fixedrate" src="https://user-images.githubusercontent.com/541276/78220425-3040f280-74ca-11ea-9552-697e1fa9cf14.png">

**Comment by kevinpapst** [comment] 2020-04-02 07:41
I think that could be a copy&paste problem from invoices.
In invoices the amount is set to one in case of a fixed rate.
For exports the pure data should be given, so I will remove it from the preview.

**Comment by randomev** [comment] 2020-04-02 07:47
Great, thanks! Export is the screen we use to enter data (manually) to our bookkeeping agency's accounting software so we use export all the time as that allows us easily to check each entry as "Exported" after we have entered it.

Thanks for fixing this, will donate via Paypal.

**Comment by kevinpapst** [comment] 2020-04-02 12:55
Thanks @randomev !!
Will be fixed with 1.9 (coming soon)

**Closed** 2020-04-08 12:50 UTC
Labels: bug, export
