### ISSUE TITLE
Users with view_rate_own_timesheet can view all users revenue in dashboard

### ISSUE THREAD

**Issue by pascal541** [kevinpapst/kimai2#1913] opened 2020-08-24 14:20 UTC
**Describe the bug**
Users with view_rate_own_timesheet permission can view the revenue of all users in the dashboard where previously it only displayed the users own revenue

**To Reproduce**
1. Give a user the view_rate_own_timesheet permission
2. Go to dashboard
3. Dashboard displays all users revenue instead of own revenue

**Screenshots**
![image](https://user-images.githubusercontent.com/7486865/91055770-64f24980-e625-11ea-9abe-3990a3733866.png)
I blurred the numbers for privacy reasons. (the user has no timesheets!)

**Additional context**
 - Kimai version: 1.10
 - PHP version: 7.4.9

**Comment by kevinpapst** [comment] 2020-08-24 15:28
Confirmed. The problem is not the widget, which should be there - the problem is the query which is executed without using the user to limit the result set. Working on a fix right now...

**Comment by kevinpapst** [comment] 2020-08-24 16:38
Fixed in master

**Closed** 2020-08-24 16:37 UTC
Labels: bug

**Comment by pascal541** [comment] 2020-08-24 17:08
Thanks for the fast fix. Is there an ETA for 1.10.1?

**Comment by kevinpapst** [comment] 2020-08-24 17:15
Somwhen between now and Sylvester? 😁 don't expect timelines for open source software.

But as GitHub Pro user I am confident you know how to switch a branch^^

**Comment by kevinpapst** [comment] 2020-08-27 09:44
@pascal541 In a couple of minutes

**Comment by pascal541** [comment] 2020-08-31 09:24
Following up on this. Teamleads can also see all revenue on the dashboard instead of only the revenue by the users in their team. I am not 100% sure if this is a bug? I can make a seperate issue if it is.

**Comment by kevinpapst** [comment] 2020-08-31 09:55
You can create another issue, but I will first work on these widgets again, when refactoring the complete dashboard to add configurability.

These widgets were created long before team permissions existed. Just assign this widget row another permission: https://github.com/kevinpapst/kimai2/blob/master/config/packages/kimai.yaml#L198
Then they won't see it anymore for now.
