### ISSUE TITLE
Request via API with X-AUTH-USER invalidates all other sessions for the (LDAP) user

### ISSUE THREAD

**Issue by schmunk42** [kevinpapst/kimai2#2873] opened 2021-10-21 11:10 UTC
**Describe the bug**
We're making API requests with a browser plugin (or postman), the first single request via API invalidates all session for the user.

**To Reproduce**
1. Go to 'Login' in a browser and login with: myuser
2. create a postman request with `X-AUTH-USER: myuser`
3. Reload or navigate to another site in browser

**Logfile**
```
kimai_1  | localhost:8001 172.17.0.5 - - [21/Oct/2021:12:59:17 +0200] "GET /de/reporting/project_view HTTP/1.1" 200 7579 "https://kimai.mydomain.de/de/timesheet/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
kimai_1  | localhost:8001 172.17.0.5 - - [21/Oct/2021:12:59:18 +0200] "GET /api/timesheets/recent?size=10 HTTP/1.1" 200 4768 "https://kimai.mydomain.de/de/reporting/project_view" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
kimai_1  | localhost:8001 172.17.0.5 - - [21/Oct/2021:12:59:22 +0200] "POST /api/activities HTTP/1.1" 400 768 "-" "PostmanRuntime/7.28.4"

===> All existing browser sessions are invalid after the above request

kimai_1  | localhost:8001 172.17.0.5 - - [21/Oct/2021:12:59:31 +0200] "GET /de/reporting/project_view HTTP/1.1" 302 792 "https://kimai.mydomain.de/de/timesheet/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"

===> Browser session still exists, but it's missing _csrf/authenticate and _csrf/entities_multiupdate

kimai_1  | localhost:8001 172.17.0.5 - - [21/Oct/2021:12:59:31 +0200] "GET /de/login HTTP/1.1" 200 1313 "https://kimai.mydomain.de/de/timesheet/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
```

**Additional context**
 - Kimai version: 1.15.1
 - PHP version: 7.x
 - Device: Desktop/Laptop
 - Browser Chrome, Postman/Custom Browser Plugin
 - Activated Settings/Plugins: LDAP, Taskmanagement

---

(addon question) Why are REST requests create a session at all?

**Comment by handcode** [comment] 2021-11-05 13:00
@schmunk42 : It's not a session problem, it's a user comparison problem.

@kevinpapst  correct me, but as far as I can see every request checks if the user or one of its (auth) properties has changed and if so, all sessions initialized before the change are invalidated. Makes sense if e.g. the permissions have changed.

The problem in our setup arises from two pieces of code, both of which potentially modify the User object, but which in my opinion are both not needed at all.

However, it would be enough to change one of the parts.

**Part 1:**

`\App\Security\TokenAuthenticator` implements `PasswordAuthenticatedInterface` which requires the implementation of the `getPassword()` Method.

`\App\Security\TokenAuthenticator::getPassword()` returns the token.
Effect: User password attribute will be changed if not set.

But Token authentication does not need a password, only the token has to be checked and not the password, so i think we can remove the Method (the PasswordAuthenticatedInterface implementation) at all.

**Part 2:**

`\App\Ldap\LdapUserHydrator::hydrateUser()` sets the user password to an emtpy string on every login.
Effect: User password attribute will be changed if set.

@kevinpapst : your comment in the code indicates that you had once implemented this so that a Ldap users can not change their passwords. But this is IMHO no longer necessary, because the "can reset" check is now done via `user->isInternalUser()` , or the `user->auth` attribute.

*Sidenote*: same behaviour in `\App\Saml\User\SamlUserFactory::hydrateUser()`, c&p ?

**Conclusion:**
The two places in the code both try to do something that in my opinion is not necessary (anymore) and in combination Ldap & API Auth cause a user object to constantly change and therefore the (ldap) user has to re-login constantly.

**Fix:**
Our problem is fixed in my test setup when I either remove setting the password to an empty string in `\App\Ldap\LdapUserHydrator::hydrateUser()` (Line 78) , or remove the `TokenAuthenticator::getPassword()` method from the code.  I also can remove both and do not see any problems, but maybe i missed something ;-)

@kevinpapst : i can create a PR for either one or both of the issues. But as I said, maybe I missed something completely. It' s your decision ;-)

**Comment by kevinpapst** [comment] 2021-11-05 13:35
Wow @handcode  👍 

I would not have come up with that solution, without a working LDAP setup - that is great feedback and quite some debug skills you have there 😁

Let me test if the same behavior happens with SAML. I'll have a quick look at the code, but I guess your view is fresh now, so if you already have an opinion: go ahead and sent in a PR.

**Comment by kevinpapst** [comment] 2021-11-05 21:32
Alright, this is one of the bugs that you don't believe unless you see it for yourself.
I can confirm it for SAML. 
I'll need to dig a bit deeper, which should be easy thanks to the great input by @handcode

**Comment by kevinpapst** [comment] 2021-11-05 23:23
Okay, I remember at least what 1) was about and will leave some comments in the code: The `PasswordAuthenticatedInterface` takes care of rehashing passwords inside the Symfony security system, if it was previously hashed with an algorithm that is now super-seeded by a newer/better/safer alternative.

So this method should stay. I just don't know why Symfony triggers it on every authentication and not ONLY when a password upgraded is needed.

So I went with 2) and do not reset the password in the hydration process, unless needed.
You could help testing this PR: #2916

The code needs to be rewritten in the near future anyways, because the Symfony framework added an entirely new authentication system, which needs to be implemented with the move to the next major version.

**Comment by schmunk42** [comment] 2021-11-10 09:25
While the fix works, the root-cause IMO is, that the functionality/interface(s) for Password-Rehashing simply update `password` of the user object and not `api_token` when using in API context.

FYI: We tried to write an `x` into the db, so that password is not empty, but it seems that the framework is checking the validity, which fails and then also updates it.

**Comment by kevinpapst** [comment] 2021-11-10 09:39
Holy crap, thanks for explicitly pointing that out. What a bug and I did not recognize it at all. 
Thanks, I removed the interface from the TokenAuthenticator. 
Guess it is ready for merge now?

**Comment by schmunk42** [comment] 2021-11-10 10:24
> Guess it is ready for merge now?

Yes :)

**Comment by handcode** [comment] 2021-11-10 10:27
ACK.
Btw. If you want the magic rehashing for the api_token, that has to be implemented differently. The PasswordAuthenticatedInterface, as I understand it, "only" takes care of the passward attribute.

**Comment by kevinpapst** [comment] 2021-11-10 10:29
Yeah, not for now. When I upgrade to Symfony 5 or 6 the Security system has to be changed massively, that is the time when it can be re-introduced.

**Comment by kevinpapst** [comment] 2021-11-10 10:35
Thanks for all your input, that was really helpful 👍 

More of that is very welcome 😁

**Closed by kevinpapst** 2021-11-10 10:35 UTC
Labels: bug
