### ISSUE TITLE
How to configure LDAP connexion to Kimai2

### ISSUE THREAD

**Issue by Gyrfalc0n** [kevinpapst/kimai2#1379] opened 2020-01-15 08:47 UTC
Good morning, sir, 
I'm trying to set up the connection to my Kimai2 server via **LDAP**. However I can't get my server to communicate with my domain controller. 

Zend keeps giving me the error "_0x51 - Can't contact LDAP server_". This error occurs regardless of the port used. I'm in a dev environment with the latest version on the master branch.

I'm using PHP v7.4. I should point out that Kimai2 in my configuration is intended to be accessible only locally.

I tried to connect the Active Directory instead of LDAP alone but without more success.

**My question is**: do I need to install and set up a local OpenLDAP on the machine hosting the Kimai2 server, in order to make a kind of bridge between OpenLDAP and my domain controller, so that the users of my AD can connect with their account.

**Local.yaml**
```security:
    providers:
	chain_provider:
            chain:
                providers: [kimai_ldap]
    firewalls:
	secured_area:
            kimai_ldap: ~

kimai:
    user:
	registration: false
        password_reset: false
    ldap:
	connection:
            host: serveur-dc1.company.local
            username: CN=Administrateur,CN=Users,DC=company,DC=local
            password: Password
            accountDomainName: company.local
            accountDomainNameShort: COMPANY
            accountFilterFormat: (&(objectClass=Person)(sAMAccountName=%s))
        user:
            baseDn: ou=Comptes-mail,dc=company,dc=local
            filter: (&(objectClass=Person))
            usernameAttribute: samaccountname
            attributes:
                - { ldap_attr: mail, user_method: setEmail }
                - { ldap_attr: displayname, user_method: setAlias }
                - { ldap_attr: samaccountname,  user_method: setUsername }
        role:
            baseDn: dc=company,dc=local
            filter: (&(objectClass=group))
            groups:
                - { ldap_value: Leads, role: ROLE_TEAMLEAD }
                - { ldap_value: Domain Admins, role: ROLE_SUPER_ADMIN }
                - { ldap_value: Domain Users, role: ROLE_USER }

```

**Comment by kevinpapst** [comment] 2020-01-15 11:17
Hi @Gyrfalc0n 

> Zend keeps giving me the error "_0x51 - Can't contact LDAP server_". This error occurs regardless of the port used. I'm in a dev environment with the latest version on the master branch.

I have never seen this error.

> I tried to connect the Active Directory instead of LDAP alone but without more success.

Both should work if properly configured. Is the error from the var/logs/dev.log file?

> **My question is**: do I need to install and set up a local OpenLDAP on the machine hosting the Kimai2 server, in order to make a kind of bridge between OpenLDAP and my domain controller, so that the users of my AD can connect with their account.

No, that is not required. LDAP is a pain to configure initially (at least for me), but then it just works. I know there are users who use Kimai with an AD successful. Search the closed issues, maybe you find something there. You have see the AD section at the end of the LDAP docs?

**Comment by Gyrfalc0n** [comment] 2020-01-15 13:15
Thanks for your answer, I looked at the closed issues about AD or LDAP and I still can't get rid of the error I get.

After configuring my **local.yaml** according to my first message, I get the following error after an attempt to login by an AD user : 

```
Authentication request could not be processed due to a system problem
```
You can see the __**0x51 error**__ from Zend framework here : 
**dev.log**

```
[2020-01-15 14:07:32] app.ERROR: Zend\Ldap\Exception\LdapException: 0x51 (Can't contact LDAP server): ldap://serveur-dc1.xxxxxxxx.local:389 in /var/www/kimai2/vendor/zendframework/zend-ldap/src/Ldap.php:991 Stack trace: #0 /var/www/kimai2/src/Ldap/LdapDriver.php(94): Zend\Ldap\Ldap->bind() #1 /var/www/kimai2/src/Ldap/LdapManager.php(66): App\Ldap\LdapDriver->search() #2 /var/www/kimai2/src/Ldap/LdapManager.php(55): App\Ldap\LdapManager->findUserBy() #3 /var/www/kimai2/src/Ldap/LdapUserProvider.php(47): App\Ldap\LdapManager->findUserByUsername() #4 /var/www/kimai2/vendor/symfony/security-core/User/ChainUserProvider.php(56): App\Ldap\LdapUserProvider->loadUserByUsername() #5 /var/www/kimai2/src/Ldap/LdapAuthenticationProvider.php(62): Symfony\Component\Security\Core\User\ChainUserProvider->loadUserByUsername() #6 /var/www/kimai2/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php(65): App\Ldap\LdapAuthenticationProvider->retrieveUser() #7 /var/www/kimai2/vendor/symfony/security-core/Authentication/AuthenticationProviderManager.php(80): Symfony\Component\Security\Core\Authentication\Provider\UserAuthenticationProvider->authenticate() #8 /var/www/kimai2/vendor/symfony/security-http/Firewall/UsernamePasswordFormAuthenticationListener.php(100): Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager->authenticate() #9 /var/www/kimai2/vendor/symfony/security-http/Firewall/AbstractAuthenticationListener.php(131): Symfony\Component\Security\Http\Firewall\UsernamePasswordFormAuthenticationListener->attemptAuthentication() #10 /var/www/kimai2/vendor/symfony/security-bundle/Debug/WrappedListener.php(51): Symfony\Component\Security\Http\Firewall\AbstractAuthenticationListener->__invoke() #11 /var/www/kimai2/vendor/symfony/security-bundle/Debug/TraceableFirewallListener.php(35): Symfony\Bundle\SecurityBundle\Debug\WrappedListener->__invoke() #12 /var/www/kimai2/vendor/symfony/security-http/Firewall.php(97): Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener->callListeners() #13 /var/www/kimai2/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(126): Symfony\Component\Security\Http\Firewall->onKernelRequest() #14 /var/www/kimai2/vendor/symfony/event-dispatcher/EventDispatcher.php(260): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke() #15 /var/www/kimai2/vendor/symfony/event-dispatcher/EventDispatcher.php(235): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() #16 /var/www/kimai2/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners() #17 /var/www/kimai2/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(168): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() #18 /var/www/kimai2/vendor/symfony/http-kernel/HttpKernel.php(127): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch() #19 /var/www/kimai2/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #20 /var/www/kimai2/vendor/symfony/http-kernel/Kernel.php(198): Symfony\Component\HttpKernel\HttpKernel->handle() #21 /var/www/kimai2/public/index.php(37): Symfony\Component\HttpKernel\Kernel->handle() #22 {main} {"exception":"[object] (Zend\\Ldap\\Exception\\LdapException(code: 81): 0x51 (Can't contact LDAP server): ldap://serveur-dc1.xxxxxxxx.local:389 at /var/www/kimai2/vendor/zendframework/zend-ldap/src/Ldap.php:991)"} []
[2020-01-15 14:07:32] doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12, t0.alias AS alias_13, t0.registration_date AS registration_date_14, t0.title AS title_15, t0.avatar AS avatar_16, t0.api_token AS api_token_17 FROM kimai2_users t0 WHERE t0.email_canonical = ? LIMIT 1 ["xxxx@xxxxxx.fr"] []
[2020-01-15 14:07:32] doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12, t0.alias AS alias_13, t0.registration_date AS registration_date_14, t0.title AS title_15, t0.avatar AS avatar_16, t0.api_token AS api_token_17 FROM kimai2_users t0 WHERE t0.username_canonical = ? LIMIT 1 ["xxxx@xxxxxx.fr"] []
[2020-01-15 14:07:32] app.DEBUG: ldap_search(ou=Comptes-mail,dc=xxxxxxx,dc=local, (&(&(objectClass=Person))(samaccountname=xxxx@xxxxxx.fr)), [array]) {"action":"ldap_search","base_dn":"ou=Comptes-mail,dc=xxxxxxxx,dc=local","filter":"(&(&(objectClass=Person))(samaccountname=xxxx@xxxxxx.fr))","attributes":["+","*"]} []
```



















Authentication request could not be processed due to a system problem

**Comment by kevinpapst** [comment] 2020-01-15 13:24
Can you reach your AD server from that server via the configured connection? 
The error indicates "LDAP SERVER DOWN". Which I would say indicates that it can't be reached. And that can have dozens of reasons... are you sure the network connection is open and accessible from Kimai server is allowed?

**Comment by Gyrfalc0n** [comment] 2020-01-15 14:20
I don't know how to test more than I did. Ping tests work both ways. An nmap test on the domain controller returns the open LDAP ports but Zend can't connect to them...

```
Host is up.
PORT    STATE    SERVICE
389/tcp filtered ldap
```

**Comment by Gyrfalc0n** [comment] 2020-01-15 15:10
Okay, with some small changes, I have a new error that seams to be less complicated : 

```
doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12, t0.alias AS alias_13, t0.registration_date AS registration_date_14, t0.title AS title_15, t0.avatar AS avatar_16, t0.api_token AS api_token_17 FROM kimai2_users t0 WHERE t0.username_canonical = ? LIMIT 1 ["enguerrand vie"] []
[2020-01-15 16:04:47] app.DEBUG: ldap_search(ou=Comptes-mail,dc=xxxxxxx,dc=local, (&(&(objectClass=Person))(mail=xxxx@xxxxxxx.fr)), [array]) {"action":"ldap_search","base_dn":"ou=Comptes-mail,dc=xxxxxxx,dc=local","filter":"(&(&(objectClass=Person))(mail=xxxx@xxxxxxx.fr))","attributes":["+","*"]} []
[2020-01-15 16:04:47] doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12, t0.alias AS alias_13, t0.registration_date AS registration_date_14, t0.title AS title_15, t0.avatar AS avatar_16, t0.api_token AS api_token_17 FROM kimai2_users t0 WHERE t0.username_canonical = ? LIMIT 1 ["xxxx@xxxxxxx.fr"] []
[2020-01-15 16:04:47] app.DEBUG: ldap_search(ou=Comptes-mail,dc=xxxxxxx,dc=local, (&(&(objectClass=Person))(mail=xxxx@xxxxxxx.fr)), [array]) {"action":"ldap_search","base_dn":"ou=Comptes-mail,dc=xxxxxxxx,dc=local","filter":"(&(&(objectClass=Person))(mail=xxxx@xxxxxxx.fr))","attributes":["+","*"]} []
[2020-01-15 16:04:47] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationServiceException(code: 0): Notice: Trying to access array offset on value of type bool at /var/www/kimai2/vendor/symfony/security-core/Authentication/Provider/DaoAuthenticationProvider.php:85, ErrorException(code: 0): Notice: Trying to access array offset on value of type bool at /var/www/kimai2/vendor/zendframework/zend-ldap/src/Collection/DefaultIterator.php:334)"} []
[2020-01-15 16:04:47] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"fos_user_security_login"} []
```

**Comment by kevinpapst** [comment] 2020-01-15 15:17
Hm, looks as if the result from the LDAP is not matching the expected structure.
Looks like a configuration issue.

**Comment by Gyrfalc0n** [comment] 2020-01-15 15:44
Again, thanks for your answer. I will manage to get it working.

**Comment by Gyrfalc0n** [comment] 2020-01-19 14:40
After some investigations, I figured out that the PHP version 7.4 has a different way to treat some errors. In my case, instead of returning Null, PHP returns an error from the files.

I'll try to reinstall with an older version like 7.3.

**Comment by kevinpapst** [comment] 2020-01-19 14:41
Oh wow, that sounds like a critical BC break. Can you pinpoint the places where it changed, so I can investigate as well? I have no PHP 7.4 available here, so I can't test it myself.

**Comment by kevinpapst** [comment] 2020-01-26 23:28
Unit tests are green with PHP 7.4, closing until someone else can report exact problems and we can reproduce the problems with some new tests.

**Closed by kevinpapst** 2020-01-26 23:28 UTC
