### ISSUE TITLE
Ability to create multiple timesheet records from single screen.

### ISSUE THREAD

**Issue by dzmudist** [kevinpapst/kimai2#616] opened 2019-03-05 14:00 UTC
**Is your feature request related to a problem? Please describe.**
As a user I would like to populate timesheet in the end of work day with less number of clicks as possible.
The problem is the report usually spans multiple Customers, Projects and Activites (4-5 unique combinations per day), thus in current user interface it has to be created one-by-one.

**Describe the solution you'd like**
It would be nice to have batch report creation feature, which would allow from a single screen populate multiple activities for different projects/customers, such that date is selected once per batch, total hours can be seen as a sum of all entered activities in order to check actual vs expected total hours per day and save button persists all the records at one hit.

**Additional context**
Here is example of one day report:
Customer1/ProjectA/ActivityA
1 to 1 (Employee 1) (0.5h)
1 to 1 (Employee 2) (1h)

Customer1/ProjectA/ActivityB
Training (subject xxx) (1h)
Product development sync meeting (1h)
New Project P1 discussion (1h)

Customer2/ProjectС/ActivityA
HR (discuss offers, review hiring plans) (1.5h)
Time tracking (model various schemas of Customer/Project/Activity definition) (1.5h)

Customer2/ProjectD/ActivityC
Bug in product XYZ (investigate why functionality doesn't work since release N) (0.5h)
Customer request in scope of project P2 (write email with proposal) (0.5h)
Other activities (read emails, answer to adhoc questions) (2h)

**Comment by kevinpapst** [comment] 2019-03-07 01:03
Probably a duplicate of #312 ?

**Closed** 2020-11-08 02:45 UTC
Labels: duplicate
