### ISSUE TITLE
Invoice overview shows wrong values

### ISSUE THREAD

**Issue by lwndp** [kevinpapst/kimai2#3562] opened 2022-09-30 09:57 UTC
**Describe the bug**
When generating invoices / searching for open invoices in a given time period, the "Preview: Invoices" overview shows two identical sum values as well as projects for different clients. However, when opening the invoices in preview, the correct projects and sum values are shown, HOWEVER, Invoice numbers are the same on both invoices (I guess that's due to the preview,  but still confusing).

**To Reproduce**
1. Go to 'Invoices'
2. Click on 'Search'
3. See overview of (open) invoices

**Logfile**
```
N/A
```

**Additional context**
 - Kimai version: 1.25.0
 - PHP version: 7.4.30
 - Device: MacBook Pro
 - Browser: Brave

![Screen Shot 2022-09-30 at 11 44 17](https://user-images.githubusercontent.com/55749141/193245340-5405e268-e7aa-4f14-a392-18d00783fd97.jpg)
![Screen Shot 2022-09-30 at 11 45 24](https://user-images.githubusercontent.com/55749141/193245346-d335b1f4-ea1d-454c-b6e8-707899518c16.jpg)
![Screen Shot 2022-09-30 at 11 45 29](https://user-images.githubusercontent.com/55749141/193245349-560eca3d-95d5-490c-b9c4-5f4ebb273f07.jpg)

**Comment by kevinpapst** [comment] 2022-10-01 10:35
I do not understand what should be wrong and I cannot reproduce it.
I need more input.

**Comment by lwndp** [comment] 2022-10-01 11:19
Sorry if I wasn't clear in my bug report.

Yesterday, I wanted to export two invoices with worked hours in the past month. When searching for open invoices in the invoices tab, the results showed two identical total prices & duration, which were **not correct** (at this point I hadn't downloaded any one of them); see 1st screenshot. When I opened the results in preview, the total prices & hours were correct and differed between the two invoices, as expected; see 2nd & 3rd screenshots.
Does this clarify the issue for you?

What other info do you need from me for further investigation?

**Comment by kevinpapst** [comment] 2022-10-01 11:27
The preview uses the exact same data as the download. Please try to reproduce it in the demo, so you can share data and we can investigate together.

**Comment by lwndp** [comment] 2022-10-01 11:51
Can't reproduce on demo either. I created customer1 & customer2 & respective projects and tasks. Activities would apply to both customers & their projects as in my case as well. Export preview shows correct values.  However, this differs on my system, which is the unchanged official latest release.

Illustrating the problem again on my end:
![Screen Shot 2022-10-01 at 13 45 50](https://user-images.githubusercontent.com/55749141/193408152-708bb858-dd4b-4b5c-8b32-bdac14e5e4b8.jpg)

**Comment by kevinpapst** [comment] 2022-10-01 11:59
Can you please show me your search form and especially the invoice template configuration

**Comment by lwndp** [comment] 2022-10-01 13:05
There you go. I removed data in the fields Adresse, Kontakt, Zahlungsinformationen & Bankverbindung for privacy reasons.

Invoice format is PDF -> Rechnung

![Screen Shot 2022-10-01 at 15 01 32](https://user-images.githubusercontent.com/55749141/193410843-659255dd-68a8-4d11-ae0a-f34f9a7a2359.jpg)
![Screen Shot 2022-10-01 at 15 02 53](https://user-images.githubusercontent.com/55749141/193410844-7c50d6d5-f09b-4ad4-af40-0d32dc32fd70.jpg)

**Comment by kevinpapst** [comment] 2022-10-01 13:53
FYI @LiaraAlis looks like the "Small business plugin" is active. 

Closing here, please re-open at the repository https://github.com/LiaraAlis/kimai2-SmallBusinessRuleBundle

**Closed by kevinpapst** 2022-10-01 13:53 UTC
Labels: bug, waiting for feedback

**Comment by lwndp** [comment] 2022-10-01 14:08
@kevinpapst it's indeed the small business plugin causing the issue. Thanks a lot for assisting 🙏🏼

**Comment by LiaraAlis** [comment] 2022-10-01 14:18
@kevinpapst I already fixed this issue with v1.0.1 of the plugin that was released a few days ago. Please update the plugin to the new version. 😉
