### ISSUE TITLE
API: add create, update and delete tag

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#869] opened 2019-06-19 16:13 UTC
Is it possible in Kimai for a user to create tasks using the API like do all actions using the API but not be able to do the same from the frontend. We would like to call the API for a user and create timesheet records etc, and the user should be able to log into the frontend see all records but not be able to delete or edit them. The deletion edit etc from the frontend should only be available to the admin user.

Can we have something like an API user mode where everything is possible from the backend and just readonly viewing from the frontend. 

The idea is users have no control over when the start and stop task this would be created through the API from actions from a frontend application that they use for work, but to check if a record got created etc they would use the fronend to see things. 

This may be possible from the existing permissions options but if you could guide me it would be good.

**Comment by kevinpapst** [comment] 2019-06-19 16:36
Tags creation via API is not yet possible. 
I like your idea and hope you manage to build this app! 
There is documentation on the permissions: http://www.kimai.org/documentation/permissions.html

**Comment by kevinpapst** [comment] 2019-06-19 16:37
Duplicate of #868

**Closed by kevinpapst** 2019-06-19 16:37 UTC
Labels: API, feature request
