### ISSUE TITLE
Additional status indicators for a field (tag field) more like lables which are globally assigable and appear for each task a user is working on or has started

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#769] opened 2019-05-09 16:26 UTC
**Is your feature request related to a problem? Please describe.**
Currently the tags filed does not exist, if it is created an option to add label to it can really help. In some cases certain tasks the user is working on has to be prioritied or in some cases have to be stopped. Having an option of a label can meet this requirement. Where one label can indicate something an another something else. If its labelled as priority the user can try to complete it faster and so on.

**Describe the solution you'd like**
Ability to add a label to a tag. It more like additional information for a field, or actions to be performed for a value in a tag. Something more like that is present in git.

**Describe alternatives you've considered**
We use the desciption field to update the tag value and then export the data. Post which we identify the user working on the task and inform them via email.

**Additional context**

**Comment by kevinpapst** [comment] 2019-05-09 17:04
I don't see how this is any different than tags, which I already closed as duplicate of #604 
If you need a priority tag, don't misuse the "lunch" tag to re-prioritize it, but assign a second "high priority" tag.

**Comment by rarvin** [comment] 2019-05-13 19:06
Thanks for adding the tags feature. It is simply great, but something that can really help additionally would be a as follows.

When a user searches a tag it just lists our the tasks assigned against that specific tag. What would be great would if when a user searches against a said tag, if all of the tags that are listed (assigned) against the same task can be displayed can be really helpful. Please see if this can be done as it would meet the requirement that i had listed above.

**Comment by kevinpapst** [comment] 2019-05-22 23:28
Please open a new issue for the last point.

**Closed by kevinpapst** 2019-05-22 23:28 UTC

**Comment by kevinpapst** [comment] 2019-05-25 14:11
No need for a new issue, I fixed it in #810

**Comment by rarvin** [comment] 2019-05-26 08:31
Thanks for doing this. It would be a great functionality and enhance the
tagging function greatly.
