### ISSUE TITLE
Change view in calender

### ISSUE THREAD

**Issue by schwantuschke** [kevinpapst/kimai2#1742] opened 2020-05-25 11:31 UTC
It would be nice if the user can change the headline for entries in calender view. At the moment only I can see the activity. But i would like to see the project in the calender overview.
It's possible to create a setting to change this?

**Comment by schwantuschke** [comment] 2020-05-25 14:36
And something else. I think a filter (projects, clients...) for calender view will be nice.

**Comment by kevinpapst** [comment] 2020-05-25 14:37
You can vote for the existing issue #573

**Comment by kevinpapst** [comment] 2021-03-19 14:34
Closing as duplicate of #1703

**Closed by kevinpapst** 2021-03-19 14:34 UTC
Labels: calendar, duplicate, feature request
