### ISSUE TITLE
Admin to insert times in calendar

### ISSUE THREAD

**Issue by amanzone** [kevinpapst/kimai2#1255] opened 2019-11-15 17:05 UTC
Hello,

in my company we would need to give one administrator the possibility to add times for other users in the calendar view.

This means that in principle ad aministrator would have to possibility to insert working hours for any user.

Looking at the documentation I could not find this as a feature already available: do you think it would be possible/appropriate to do this?

As an alternative, do you have a workaround proposal we could follow?

Thanks in advance for any help you can provide.

Best regards,
Alberto

**Comment by kevinpapst** [comment] 2019-11-15 17:19
Why must it be the calendar? Use the normal timesheet administration...

**Comment by amanzone** [comment] 2019-11-18 15:32
Thanks for your quick reply.

Yes, of course it's not that it MUST be the calendar view. It's only that the lady doing this job has commented that the calendar view seems to be more user friendly (for instance one could possibly configure different colours in the calendar for different projects/activities).

**Comment by kevinpapst** [comment] 2019-11-19 18:28
I understand. 
You can already do that at Administration => Timesheets.
And the calendar view can be extended in the future to support admin access for all users.
Your company could even sponsor such a feature to get it faster...

**Comment by amanzone** [comment] 2019-11-20 09:57
Yes, that's what she's actually doing today.

I will bring up this feature request in an internal meeting and see if the company is willing to support it.
I'll come back later.

**Comment by amanzone** [comment] 2019-11-27 10:35
The decision taken was instead to use APIs with an internally designed SW to achieve faster results and performing bulk actions on timesheets.
So this feature about the calendar view would not be needed any more, at least from my side.

On the other hand if you think it could be useful we can provide the small SW we have developed to the community... Unfortunately it's designed in .NET, so I'm not sure if you will like this or not.

**Comment by kevinpapst** [comment] 2019-11-27 11:15
Sharing software as open source if always a great idea! I
'll keep this open, as I heard the request from other users as well.

**Comment by hoangduy1505** [comment] 2020-05-26 09:34
> Hello,
> 
> in my company we would need to give one administrator the possibility to add times for other users in the calendar view.
> 
> This means that in principle ad aministrator would have to possibility to insert working hours for any user.
> 
> Looking at the documentation I could not find this as a feature already available: do you think it would be possible/appropriate to do this?
> 
> As an alternative, do you have a workaround proposal we could follow?
> 
> Thanks in advance for any help you can provide.
> 
> Best regards,
> Alberto

Hi, I same you, need view on calendar

**Comment by alqu** [comment] 2020-09-08 12:18
> The decision taken was instead to use APIs with an internally designed SW to achieve faster results and performing bulk actions on timesheets.
> So this feature about the calendar view would not be needed any more, at least from my side.
> 
> On the other hand if you think it could be useful we can provide the small SW we have developed to the community... Unfortunately it's designed in .NET, so I'm not sure if you will like this or not.

Sounds like a good idea.
Nevertheless, thinking about ALL users, not only those that have a Windows PC in front of them, it sounds like a good idea to have a calendar view at hands that additionally displays other user's entries.

Use case 1: the teamlead wants to have a glimpse about what is going on this week. So the weekly calendar (Calendar -> Week) needs to be extended in the way, that all entries of his team members are displayed, of course re-using the color of each user's avatar.

Use case 2: the admin wants to have an overview of what is happening this month. He then clicks on Calendar -> Month and e.g. manually picks users by the user picker (that one from the filter menu) and voilà, there they are for the requested date range.

Of course there are more use cases, but these two would come in pretty handy.

**Comment by kevinpapst** [comment] 2022-03-18 15:04
Closing as duplicate of #1067

**Closed by kevinpapst** 2022-03-18 15:04 UTC
Labels: duplicate, feature request, calendar

**Comment by kevinpapst** [comment] 2022-05-18 20:16
Added in #3314
