### ISSUE TITLE
Allow export of data in timesheet view directly from the frontend

### ISSUE THREAD

**Issue by rarvin** [kevinpapst/kimai2#826] opened 2019-05-30 07:09 UTC
**Is your feature request related to a problem? Please describe.**
Currently there is no option to export the data that appears in the timesheet view. Allowing us to export the data to an excel would help 

**Describe the solution you'd like**

Would it be possible to allow exporting the data that we see in the timesheet screen into an excel, instead of it it opening as as a html screen or give us an option to email from the screen directly the html data. We use this to inform our users when they have not stopped a job. Currently we take screen shots and email them as attachments since the data is not exportable from the screen and wont appear in the html report either until they are stopped. 

**Describe alternatives you've considered**
Take screenshots and send them manually, this takes lot of effort and data in a image is not usable.

**Additional context**

**Comment by kevinpapst** [comment] 2019-05-30 09:37
> Currently there is no option to export the data that appears in the timesheet view

This is simply wrong.

Also this is a duplicate of #822 

I don't want to spent my time cleaning up the issue tracker. And I don't want to read the issue templates all the time. Your behaviour in this issue tracker is starting to piss me off.

**Closed by kevinpapst** 2019-05-30 09:37 UTC
