### ISSUE TITLE
Layout issue in Chrome for 1.9 related to the dots on the left of the project names 

### ISSUE THREAD

**Issue by timlegge** [kevinpapst/kimai2#1783] opened 2020-06-16 14:02 UTC
**Describe the bug**
Layout issue in Chrome for 1.9 related to the dots on the left of the project names and customers.  They overlap the text.

**To Reproduce**
1. Upgrade to 1.9
2. View the My times view

This is in the docker version but I can't think of any reason that might be an issue

**Logfile**
```
N/A - no entries
```

**Screenshots**

![layout](https://user-images.githubusercontent.com/1029883/84783753-ef805200-afbf-11ea-8f33-ef9883bb8d91.png)

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: [e.g. iPhone6s] HP Laptop
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] Version 83.0.4103.97 (Official Build) (64-bit)

Also the same in Firefox and Privacy mode

**Additional context**
 - Kimai version 1.9
 - PHP version PHP_VERSION=7.4.4

**Comment by kevinpapst** [comment] 2020-06-16 14:44
Yes, they look wrong. Do you see that on the demo as well?
I cannot reproduce it on Firefox 77.01 or Safari 13.1.
Do you have the CustomCSS Bundle?

**Comment by timlegge** [comment] 2020-06-16 16:11
Unless it was include by default I don't use the CustomCSS.  But they don't show up on the demo either...

I will refresh my test image and see from there

**Comment by kevinpapst** [comment] 2020-06-16 16:38
If thats your docker image (with mounted directories for var and public) remember that you need to replace the contents of the public directory upon update (updates assets, css, js ...)

**Comment by timlegge** [comment] 2020-06-16 18:43
Yes, I shutdown the docker container and deleted the volumes.  I need to review the upgrading info for the docker image as it is a little confusing and is lacking in details.  For my testing, I don't care about the var  volume but I will try to write up some clarifications on what it is used for that one would want to keep on upgrades and send it to @tobybatch :

1. var/data - sqlite - database (required if you are using sqlite)
2. var/sessions - required if you want to keep user's logged in after the upgrade?
3. var/packages - not sure
4. var/plugins - location of kimai2 plugins from the plugin store?

The issue appears resolved.

Thanks - hope all is well

**Comment by kevinpapst** [comment] 2020-06-16 19:08
1. I hope no-one uses sqlite in production - but this is the "official" directory that should be used by plugins to store their data (the bundles "easy-backup" or "custom css" use it for example). So this should be mounted
2. Sessions will move to the database with 1.10 (for now you need a mount if you want if you don't want your user to log in after the update)
3. Not required, just a directory that might be used in the future
4. Should be a mounted volume
5. "/public/avatars" might be important as well. Avatars will be regenerated automatically, but the background colors of the avatars might change on regeneration (and a changed avatar could be confusing)

**Comment by kevinpapst** [comment] 2020-06-16 19:10
> The issue appears resolved.

Means we can close the issue?

**Closed** 2020-06-16 19:31 UTC
Labels: question, upgrade
