### ISSUE TITLE
Swap save and close buttons on record creation

### ISSUE THREAD

**Issue by yayitazale** [kevinpapst/kimai2#1621] opened 2020-04-07 14:31 UTC
I usually click on close instead of clicking on save because the cancel/confirm buttons of the date selector confuses my mind. Green line what my mind does to confirm and yellow line what I'm asking for, to swap save and close buttons on record creation

![imagen](https://user-images.githubusercontent.com/6462849/78681560-33364b80-78ed-11ea-836b-c69b07179707.png)

Thanks

**Comment by kevinpapst** [comment] 2020-04-07 14:43
Duplicate of #1515 ? There is a solution mentioned as well.
This dialog indeed is confusing, I never noticed that.
But I will not change just one dialog. Either all buttons will be changed or none (then we need to find a solution for the datepicker).

**Comment by yayitazale** [comment] 2020-04-07 14:49
Yes duplicated, sorry.

**Comment by kevinpapst** [comment] 2020-04-13 11:53
Duplicates #151 - closing

**Closed by kevinpapst** 2020-04-13 11:53 UTC
Labels: duplicate

**Comment by kevinpapst** [comment] 2020-05-02 16:29
Rule included in CustomCSSBundle:
https://github.com/Keleo/CustomCSSBundle/releases/tag/1.2
