### ISSUE TITLE
Some default browser keys do not work in dropdowns

### ISSUE THREAD

**Issue by tdammers** [kevinpapst/kimai2#3615] opened 2022-11-01 10:50 UTC
### Describe the issue

In the time entry popup, the default browser keybindings on dropdowns/combos don't work, particularly:

- "Down" to unfold a dropdown
- Typing ahead to jump to matching entries

As a result, making a time entry requires frequent switching between keyboard and mouse.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.22.1 stable (Ayumi)

### Which PHP version are you using?

Other (please mention below)

### How do you run Kimai?

Self-Hosted

### Steps to reproduce the behavior

1. Go to 'My times'
2. Click on plus icon to create a new entry
3. Use tab key to jump to any of the dropdowns (Customer, Project, or Activity)
4. Press the 'down' key, or any letter or digit
5. The dropdown does not unfold, and does not jump to any matching entries

### Additional context

Device: Desktop PC, Debian 11
Browser: Firefox 102.4.0esr (from Debian)

PHP version unknown, because I am not the person who installed it, however I expect it to be a current stable release, and also suspect that it's not actually relevant here, since this seems to be a client-side issue.

**Comment by kevinpapst** [comment] 2022-11-01 11:25
If you hit space, the dropdown opens and you can start typing. 
Why do you need the mouse for that?

Anyway: that is not a bug, but "only" a UX issue. 
The next major version ships a new dropdown component, which behaves different. 
You can test it and tell me if it works better, demo links are in included in #2902

**Comment by kevinpapst** [comment] 2022-11-01 11:27
Closing, as this will be solved with 2.0. Thanks for taking the time to post, really appreciated 👍

**Closed** 2022-11-01 11:27 UTC
Labels: feature request, technical debt
