### ISSUE TITLE
Dublicate entry SQL-Error after deleting invoice 

### ISSUE THREAD

**Issue by cdahinten** [kevinpapst/kimai2#1914] opened 2020-08-24 15:07 UTC
I created 4 invoices:

R2020-300
R2020-301
R2020-302
R2020-303

After deleting R2020-302 in that row I can't create other invoices any more.

I assigned the corresponding timesheet-entrys as "not-exported" and retried creating the invoice, and also tried to create an invoice for another customer – but no success.

The invoice-no. are generated with R{Y}-{cy+300,4}. I use 1.10 kimai.

An exception occurred while executing 'INSERT INTO kimai2_invoices (invoice_number, created_at, timezone, total, tax, currency, due_days, vat, status, invoice_filename, customer_id, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["R2020-0303", "2020-08-24 14:33:22", "Europe\/Berlin", 0, 0, "EUR", 30, 19, "new", "R2020-0303-muster_mustervertreibs_gmb_h.docx", 4, 4]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'R2020-0303' for key 'UNIQ_76C38E372DA68207'.

![Bildschirmfoto 2020-08-24 um 16 57 09](https://user-images.githubusercontent.com/52794941/91060162-e8626980-e62a-11ea-8589-7bc40eb2f12c.png)
![Bildschirmfoto 2020-08-24 um 16 42 57](https://user-images.githubusercontent.com/52794941/91060167-e9939680-e62a-11ea-9dcd-ce957b92a008.png)
![Bildschirmfoto 2020-08-24 um 16 41 47](https://user-images.githubusercontent.com/52794941/91060170-ea2c2d00-e62a-11ea-98a1-d9ebd4202b7f.png)

I am not sure, if deleting an invoice is a legal option. Should it not be some "revoking" or "strono" and get a new invoice-no. assigned.

Does this behaviour relate to the R{Y}-{cy+300,4} feature?

Kind regards.
CD

**Comment by kevinpapst** [comment] 2020-08-24 15:09
Using SQLIte I assume?

**Comment by kevinpapst** [comment] 2020-08-24 15:13
Try to work around it with: `R{Y}-{cy+301,4}`

**Comment by cdahinten** [comment] 2020-08-24 15:13
No. It's a MySQL-Version 10.3.22 on Raspberry Pi 4 8GB Ubuntu 20.04.1 LTS with ngnix for evaluating.

**Comment by cdahinten** [comment] 2020-08-24 15:28
R{Y}-{cy+301,4} seems to work – Thank you verry much!
Maybe it would be a good idea to have the deleted invoice showing up in the list as "deleted" or "storno". 

![Bildschirmfoto 2020-08-24 um 17 19 46](https://user-images.githubusercontent.com/52794941/91063743-a63b2700-e62e-11ea-85df-935b00a6544b.png)

**Comment by kevinpapst** [comment] 2020-08-24 15:33
Yes, there should be some option to work around that issue. I am just not sure how. 
If we keep it as deleted/storno then you would have to manage it within your tax documents.
Re-opening to keep track of the bug.

**Comment by cdahinten** [comment] 2020-08-24 15:43
Yes, you are right: For as in Germany the invoice-no has to be unique and ongoing.

An option could be the dropdown in the invoices view, where I could choose "Storno" and have the invoice status updatet according to that selection.

![Bildschirmfoto 2020-08-24 um 17 37 14](https://user-images.githubusercontent.com/52794941/91065283-90c6fc80-e630-11ea-927f-687873ec85d9.png)
![Bildschirmfoto 2020-08-24 um 17 37 53](https://user-images.githubusercontent.com/52794941/91065285-915f9300-e630-11ea-9134-b829c30bf9b1.png)

**Comment by skylord123** [comment] 2020-10-26 16:28
@kevinpapst I just ran into this bug. Can we get a "deleted_at" field added to the invoice that tracks when it was deleted? Then if the invoice was deleted just hide it from the interface (maybe even add an option to the config to enable displaying deleted invoices or not so that the invoice number makes sense). This way the database count is correct still but the invoices do not display in the system (unless users want that).

In my case I accidentally generated the wrong invoice, deleted it, went to re-create it and it failed.

**Comment by kevinpapst** [comment] 2020-10-26 18:45
The problem is: from a legal view these deleted invoices should still be kept in the system (in most cases).
But: some countries enforce a rule to use invoice numbers without gaps, so having a deleted invoice (and therefor a skipped number) can lead to problems.

I am really unsure how to handle invoice deletions from a conceptual perspective.

My current idea is: 
- All invoices can be marked as invalid (hidden from the list, counter is correct)
- The only invoice that can really be deleted from the system is the last one that was generated (freeing up the last invoice number)

But how to explain that to the user besides the documentation: why does only one invoice have a "delete" action, but all can be marked as "invalid"?

**Comment by skylord123** [comment] 2020-10-27 03:52
Maybe marking the invoice Void instead of Invalid would make more sense to the end user.

Could you add a note to the top of the invoices page that explains this limitation?

I've seen other systems handle this problem by making Invoices first go to a "Draft" stage before it is published (therefor it doesn't get an invoice number until being published). This also helps alleviate issues because the end user has to view the invoice before publishing it (I've accidentally hit Save in the past when I meant to hit Preview first). I think this could help prevent people from generating invoices incorrectly and therefor getting into this problem to begin with. So maybe in addition to your fixes force the user to preview before saving the invoice?

**Comment by BeckeBauer** [comment] 2020-10-27 06:26
I am not a tax expert but I handle an incorrect invoice either 
by deleting it (if not sent to the customer yet) and using the invoice number with another customer again in order to have no 'number gap' or
by issuing a credit note (containing a 'C' infront of the invoice number so that the invoice number already indicates that it is no invoice). 
Furthermore, there should be an option to correct the invoice content later on, e.g. if there was an subsequent agreement with the customer to apply a reduction. 
In my view, maximum flexibility were appriciated (since I also assume that every company has a slightly different practise). I admit that more flexibility causes the user to make more errors but I doubt that there is an 'one catches all solution' wich is also user friendly (considering that the invoice numbers are connected tax rules 😬)

**Comment by yroberttissot** [comment] 2021-06-02 14:41
hello, I had that problem again with Kimai 1.13. I will try the workaround

**Closed** 2021-11-15 18:21 UTC
Labels: bug, invoice
