### ISSUE TITLE
simple timesheet entry based on week

### ISSUE THREAD

**Issue by zeezhao** [kevinpapst/kimai2#2298] opened 2021-01-27 10:26 UTC
Thanks for your app! It would be great to have a simple timesheet entry similar to the view below - a weekly entry with all the tasks. This will make entry for users easier. Thanks

<img width="526" alt="timesheet-entry-simple" src="https://user-images.githubusercontent.com/51227714/105977835-c1044280-6089-11eb-9a88-c865e4684786.png">

**Comment by HeinzWuert** [comment] 2021-01-27 13:03
A date range or number of days in the normal timesheet might be a simplier solution for multipicated entries.

**Comment by kevinpapst** [comment] 2021-01-27 13:10
That was requested multiple times before and I admit that it might be a good feature in case you use a time-tracking mode that allows to configure a default start time. 

But I am 100% certain, that this one here is a duplicate of an already existing issue - I am just too lazy to search it right now. If anyone finds it, please post the id / url.

**Comment by zeezhao** [comment] 2021-01-27 13:22
Similar to:
https://github.com/kevinpapst/kimai2/issues/312

https://github.com/kevinpapst/kimai2/issues/1813

Thanks

**Comment by kevinpapst** [comment] 2021-01-27 13:31
Thanks for the links, please add your 👍 votes on the initial post in the other issues. I will close here to avoid confusions.

**Closed by kevinpapst** 2021-01-27 13:31 UTC
Labels: duplicate, feature request
