### ISSUE TITLE
Error on importing v1 timeSheets

### ISSUE THREAD

**Issue by hh-ams** [kevinpapst/kimai2#645] opened 2019-03-20 23:48 UTC
When i run the v1-Import, i get the following error-message;

`Importing timesheets, please wait
............................................................

 [ERROR] Object(App\Entity\Timesheet).project:
             Project mismatch, project specific activity and timesheet project are different. (code
         xd5hffg-dsfef3-426a-83d7-1f2d33hs5d86)

 [ERROR] Failed to import timesheet records: Failed to validate timesheet record: 70
         #0 /var/www/kimai2/src/Command/KimaiImporterCommand.php(303):
         App\Command\KimaiImporterCommand->importTimesheetRecords(Object(Symfony\Component\Console\Style\SymfonyStyle),
         Array, Array, Array)
         #1 /var/www/kimai2/vendor/symfony/console/Command/Command.php(255):
         App\Command\KimaiImporterCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #2 /var/www/kimai2/vendor/symfony/console/Application.php(911):
         Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #3 /var/www/kimai2/vendor/symfony/framework-bundle/Console/Application.php(89):
         Symfony\Component\Console\Application->doRunCommand(Object(App\Command\KimaiImporterCommand),
         Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
         #4 /var/www/kimai2/vendor/symfony/console/Application.php(262):
         Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(App\Command\KimaiImporterCommand),
         Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
         #5 /var/www/kimai2/vendor/symfony/framework-bundle/Console/Application.php(75):
         Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #6 /var/www/kimai2/vendor/symfony/console/Application.php(145):
         Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),
         Object(Symfony\Component\Console\Output\ConsoleOutput))
         #7 /var/www/kimai2/bin/console(39):
         Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
         #8 {main}
`

How to fix that? May you send me an SQL-Query, to identiy the faulty timeSheets (if this is really the problem)?

PHP Version 7.2

**Comment by hh-ams** [comment] 2019-03-21 00:42
I determined the relations around timeEntryID 70 assuming that the error-message is useful.
On the v1-database

select t.timeEntryID, t.projectID, t.activityID, t.userID, gu.groupID, gu.membershipRoleID from kimai_timeSheet t inner join kimai_groups_users gu on t.userID = gu.userID inner join kimai_groups_projects gp on t.projectID = gp.projectID and gu.groupID = gp.groupID inner join kimai_groups_activities ga on t.activityID = ga.activityID and gu.groupID = ga.groupID where timeEntryID = 70;

gives exactly one result. So if i am right, i can't see a problem with a missmatching project  or a missmatching activity here.
What stands out is that the entry with timeEntryID 70 is just the last one by time of a project.

**Comment by kevinpapst** [comment] 2019-03-21 01:08
The created timesheet entry has an invalid mapping: the project does not match the activity. 
There is either a bug in the importer or the original data is invalid ... it might work, but might be logically wrong, as Kimai 1 doesn't know anything about data integrity.
Try to delete the row and see if the import works then.

**Comment by chipee** [comment] 2019-03-22 17:41
Hello,
I also have this problem, so I wish to share my thoughts hoping it help resolving the issue.

At the beginning I had problem with users, customers and timeSheet imports. I looked what was the entries causing the issue and it **seem to be related to characters encoding**.

I use mariadb as backend. Since database of the kimaiV1 is not accessible from the kimaiV2, I did a mysqldump to move the data and import it into a temporary database where kimaiV2 can do his import. No matter how I import / export the database, the imported data end up with messed characters encoding. Characters like: 'é', 'è', 'ç' are transform into a '?'. Maybe here I'm missing something with mysqldump tool.

To install kimaiV2, I used the official docker image kimai/kimai2:prod build 4f893c3 with the official mariadb:latest id: 233f064f3a7e36ff9484aa772ac4325fd8df6a44d421392817f8e18a74a94164

Hope this help.

**Comment by kevinpapst** [comment] 2019-03-22 18:03
The error message is clearly related to a wrong mapping of activity and project.
You write you had the same error but the imported data has wrong encoding.
So did the import work or did you check the partially imported data?

Character encoding can be caused by several reasons. One of the main problems is Kimai 1, which was using a non-utf8 encoding for a long time. Can one of you share the database dump, so I can test this on my machine?
I cannot reproduce the problem and have no idea what might be causing it.

**Comment by chipee** [comment] 2019-03-22 18:22
@kevinpapst My boss agree to share the dump but not publicly. May I send an email to kevin at the kevinpapst.de domain?

**Comment by kevinpapst** [comment] 2019-03-22 18:31
Yes 👍

**Comment by mikevas** [comment] 2019-03-22 21:22
Same problem here! Need another db dump maybe?

**Comment by kevinpapst** [comment] 2019-03-22 21:44
The first dump had just one problem: Kimai 1 did not require an email for a user account, but Kimai 2 does. I will not implement a workaround for that "data problem" as I do not want to generate random emails, which are used for security features (login, password reset).

So if you see a failure like that one:
```
Failed to import users: Failed to validate user: <username>
         #0 /kimai2/src/Command/KimaiImporterCommand.php(255):
         App\Command\KimaiImporterCommand->importUsers(Object(Symfony\Component\Console\Style\SymfonyStyle), 'test12',
         Array, Array)
```
To fix it, you have to go to your Kimai 1 database and fill in values in the ` address`  column in every row in table `kimai_users`.

The character encoding was not reproducible by me. 
I imported with a command like that:
```
bin/console doctrine:schema:drop --force && bin/console doctrine:schema:create && bin/console kimai:import-v1 "mysql://kimai:kimai@127.0.0.1:3306/kimai2_justanotherimport?charset=utf8" "kimai_" "test12" "CH" „USD"
```
The important part is:
```
bin/console kimai:import-v1 "mysql://kimai:kimai@127.0.0.1:3306/kimai2_justanotherimport?charset=utf8" "kimai_" "test12" "CH" „USD"
```
what could be further stripped down to:
```
mysql://user:password@127.0.0.1:3306/database?charset=utf8
```
@mikevas what command did you use?

**Comment by kevinpapst** [comment] 2019-04-05 13:20
With the help of another dump I could find and fix the problem. 
Please test PR #679 and leave your feedback there.

**Closed by kevinpapst** 2019-04-05 13:20 UTC

**Comment by hh-ams** [comment] 2019-04-05 18:39
Thanks, i will do and get in touch soon.

**Comment by hh-ams** [comment] 2019-04-05 19:07
That fixed it. All timeSheets got imported well, also the  records, that caused problems. Thanks.
