### ISSUE TITLE
Add Button next to Customer Field

### ISSUE THREAD

**Issue by Bjoern3003** [kevinpapst/kimai2#1291] opened 2019-11-28 14:02 UTC
I think it could be very nice, if there is a add Customer Button next to the select field.

Maybe also a Link in the Dropdown, if no Entry where found.

https://drive.google.com/file/d/1LvwVflw-NtjYx4RZPfA-SG1KyMcvWodI/view

After submitting Customer Form, the Customer should added to the Formfield of the parent form, and selected.

**Comment by kevinpapst** [comment] 2021-07-13 11:52
Closing, this is a duplicate of #621

**Closed by kevinpapst** 2021-07-13 11:52 UTC
Labels: duplicate, feature request
