### ISSUE TITLE
Selectbox "Art der Auswahlboxen in Formularen" gone since v1.7

### ISSUE THREAD

**Issue by alqu** [kevinpapst/kimai2#1394] opened 2020-01-20 09:33 UTC
I installed **v1.7** over an existing **v1.6.2** instance.
Everything seems to work as intended, but I noticed that one feature is suddenly gone:
The selectbox, which decides if you have select2-JS-Dropdowns or the built in Select boxes in the frontend.
This is not a big issue, but renders the workflow unnecessary awkward - there is no way to pop up the Select2-Selectboxes via Keyboard, which was easily doable with ordinary HTML Select lists (just a "cursor down").

Was this breaking change intended?

**To Reproduce**
1. Install Kimai v1.7
2. Go to Settings / theme
3. Normally there should be a selectbox "Type of select-boxes in forms" which is not there anymore

**Screenshots**
In v1.7, it looks like:
![image](https://user-images.githubusercontent.com/12250845/72714598-4435b300-3b6f-11ea-9a15-97b5bbf630c2.png)
...and looked in v1.6.2 like:
![image](https://user-images.githubusercontent.com/12250845/72714945-df2e8d00-3b6f-11ea-94a8-b264efb4985a.png)

**Comment by kevinpapst** [comment] 2020-01-20 11:11
Yes the change was intended. But impressively quick response. 

> This is not a big issue, but renders the workflow unnecessary awkward - 

I'd say this is an XOR - either not a big issue or awkward 😁 

> there is no way to pop up the Select2-Selectboxes via Keyboard

Works fine here with space. I will have a look if that behavior can be changed.

**Comment by kevinpapst** [comment] 2020-01-20 12:12
And btw, you could ask in the Select2 repository if they have a fix for this.
The issue was reported over 2 years ago, is closed but still not fixed: https://github.com/select2/select2/issues/4514

**Comment by alqu** [comment] 2020-01-20 13:31
OKOK, I see the issue there. A 10 mile long ticket regarding keyboard issues on a simple control WTF.
I guess it will never be solved, but maybe in version 4 which is not ready yet...

Instead of relying on select2 I had a quick look at https://selectize.github.io/selectize.js/ - which is also relying on jQuery and supports all use cases.

OK, would be a bit of a tedious task, but you would gain a signicantly better supported component (12k+ stars).

My 2 cents.

**Comment by kevinpapst** [comment] 2020-01-20 13:40
Seems the developer of Select2 is not that much of a keyboard person when using forms.

But Selectize wont't work. I tried that already and it has other severe bugs. I spent easily more than 15 hours with these enhanced select boxes and Select2 was by far the best of the ones I tried (yes, I tried chosen as well).

If anyone wants to give it another try, I am happy to assist with the PR. 

If it is a bug problem for you, you can deactivate it adding a `return false;` before this line:
https://github.com/kevinpapst/kimai2/blob/master/src/Form/Extension/EnhancedChoiceTypeExtension.php#L41

**Comment by alqu** [comment] 2020-01-20 14:14
Thanks for your help. Will have a look at the above code tweak.

Interestingly does the "drop in replacement for selectboxes" as they claim also not work properly in their example: https://select2.org/dropdown - if you try to select something, it only works with prepending a "space" in order to get the box opened.

Else, I talk to the customer and inform them on how to properly select stuff.

**Comment by kevinpapst** [comment] 2020-01-26 23:07
As I have no plans to allow deactivation of the JS plugin any longer I am closing this one here.

**Closed by kevinpapst** 2020-01-26 23:07 UTC
Labels: wontfix
