### ISSUE TITLE
timesheet bulk update: make activity optional for global activities

### ISSUE THREAD

**Issue by BeckeBauer** [kevinpapst/kimai2#3401] opened 2022-07-06 08:46 UTC
Sometimes, we need to rebook several timesheet entries to another customer. Then, the bulk processing works well. However, it is required to select one activity which then overwrites the recorded activities for each of the selected timesheet entries. 

In our case (and probably in the most cases), activities are available to all customers / projects. Thus, would it be possible to make the selection of an activity optional? Then, when bulk transferring, everything remains untouched except for the customer name. 

Only if there were a customer/project related activity the system could show an error message and/or require the user to select a generally available activity for such entries.

**Comment by kevinpapst** [comment] 2022-07-06 09:52
Yeah, that is a known limitation right now. 
I could check if all entries have a global activity and then make the change optional, everything else gets too complicated.

**Comment by BeckeBauer** [comment] 2022-07-06 11:56
That would be perfect for us (since we do not use non-global activities) 👍

**Comment by kevinpapst** [comment] 2022-10-18 22:47
Closing, duplicate of #2338

**Closed by kevinpapst** 2022-10-18 22:47 UTC
Labels: duplicate, feature request
