### ISSUE TITLE
Installation PHP Fatal error

### ISSUE THREAD

**Issue by MartinGutzeit** [kevinpapst/kimai2#1397] opened 2020-01-20 14:13 UTC
Hallo i need your help.
I am trying to set up a test environment for evaluation.
I run the installation script in the Kimai2 directory. Then I get this error message

kimaiadmin@cmcsrvkim:~/kimai2$ sudo bin/console  kimai:install -n

PHP Warning:  require(/home/kimaiadmin/kimai2/bin/../vendor/autoload.php): faile
d to open stream: No such file or directory in /home/kimaiadmin/kimai2/bin/conso
le on line 12
PHP Fatal error:  require(): Failed opening required '/home/kimaiadmin/kimai2/bi
n/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/kimaiadmin/
kimai2/bin/console on line 12`

I found these files on the server.
I don't know if these are the right files?
I can't set the correct path in "Console".

/usr/share/phpmyadmin/phpMyAdmin-5.0.1-all-languages/vendor/google/recaptcha/src/autoload.php
/usr/share/phpmyadmin/phpMyAdmin-5.0.1-all-languages/vendor/autoload.php

**Additional context**
 - Ubuntu Ubuntu Linux 18.04.3
MySQL-Version 5.7.28
Apache Version 2.4.29
 - Kimai version 2
 - PHP version 7.2

regards Martin

**Comment by kevinpapst** [comment] 2020-01-20 14:15
Read the installation docs again and don't try to skip steps:
https://www.kimai.org/documentation/installation.html#recommended-setup

Hint: it starts with `composer` 😁

**Comment by MartinGutzeit** [comment] 2020-01-20 14:31
Composer is installed

[sudo] password for kimaiadmin:
All settings correct for using Composer
Downloading...

Composer (version 1.9.2) successfully installed to: /bin/composer
Use it: php bin/composer

**Comment by kevinpapst** [comment] 2020-01-20 14:32
great! but that was only step 1... read the docs...

**Comment by kevinpapst** [comment] 2020-01-20 14:48
After installing composer you have to use it (in the kimai directory) to install the dependencies:
composer install --no-dev --optimize-autoloader

**Comment by MartinGutzeit** [comment] 2020-01-20 14:49
I did the installation according to the instructions. But somewhere I have a mistake but I don't know where.

**Comment by kevinpapst** [comment] 2020-01-20 15:00
Is there a directory called /home/kimaiadmin/vendor/ with the file autoload.php inside?

If not, I can only repeat
> you have to use it (in the kimai directory) to install the dependencies: composer install --no-dev --optimize-autoloader

**Comment by MartinGutzeit** [comment] 2020-01-20 15:07
i am too stupid

**Comment by kevinpapst** [comment] 2020-01-20 15:09
the thing is: helping is complicated if the person doesn't provide enough input or doesn't answer the question. tell me exactly what you did and provide as many input as possible, so I can hopefully see where the problem is

**Comment by MartinGutzeit** [comment] 2020-01-20 15:13
is it possible to start a teamviewer session?

**Comment by kevinpapst** [comment] 2020-01-20 15:14
If you want payed support, please contact me via email

**Comment by MartinGutzeit** [comment] 2020-01-20 15:27
Can we make phone calls? Since I do not know the conditions, I would have to clarify this with the management.

**Comment by MartinGutzeit** [comment] 2020-01-20 15:27
MGutzeit@cmc-Koeln.de

**Comment by kevinpapst** [comment] 2020-01-26 23:08
Closing, as this is not a Kimai bug.

**Closed** 2020-01-26 23:07 UTC
Labels: installation, question
