### ISSUE TITLE
Overlapping Tooltip after Calendar Event is created

### ISSUE THREAD

**Issue by blaue-mango** [kevinpapst/kimai2#1807] opened 2020-07-08 07:53 UTC
**Describe the bug**
After you create a new calendar item in calendar view, a popup opens at your mouse location, which does not automatically dismiss and stays in the way, even if you try to create a new item.

If you ignore it, you even get multiple popups to the point where the create screen is unusable.

**To Reproduce**
1. Go to Kalender
2. Switch to Weekly View
3. Use Dragndrop to create a new calendar item and fill in the required information
4. Save the item
5. Notice how a popup of the item, where your mouse is, opens and never closes again, even when you're trying to create a new item it stays in view.

**Screenshots**

![image](https://user-images.githubusercontent.com/32264292/86892229-4204e800-c100-11ea-9dcc-6cd436e52d21.png)

![image](https://user-images.githubusercontent.com/32264292/86892652-d40cf080-c100-11ea-8fe8-7b9186c41d3c.png)

Ignoring the fixed popups will block the view even more:

![image](https://user-images.githubusercontent.com/32264292/86898621-3e299380-c109-11ea-9302-96b4cb716c7c.png)

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: Desktop computer
 - OS: Windows 10
 - Browser Google Chrome 
 - Version 83.0.4103.116 (Offizieller Build) (64-Bit)

**Additional context**
 - Kimai 2 1.9 stable (Ayumi)
 - PHP version 7.3.18

**Comment by kevinpapst** [comment] 2020-07-08 13:34
Duplicate of #1448

**Closed** 2020-07-19 12:56 UTC
Labels: duplicate
