### ISSUE TITLE
my inner of the public directory is invisible

### ISSUE THREAD

**Issue by karthikalsv** [kevinpapst/kimai2#1029] opened 2019-08-13 12:06 UTC
Hi Kevinpapst,
              I installed my kimai2 and when i run the public/index.php file in chrome .The webpage is white blank .
I opened my public directory is also coming white blank in the browser . but other directory are visible and able to run .

**Comment by kevinpapst** [comment] 2019-08-13 12:10
Duplicate of #1013

**Closed by kevinpapst** 2019-08-13 12:10 UTC
