### ISSUE TITLE
Suggestion Date/Time Picker for Mobiles

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai2#1304] opened 2019-12-05 07:31 UTC
Not an issue, not for Kimai, this kind of date/time picker for smartphones.
https://github.com/PuffoCyano/Range-Time-Picker-Dialog
Usibility of the timesheet on smartphones isn't as well as it could be.
Maybe there is an Android developer who is able to provide such a simple variant only for entering date/time, activity and remark.
Everything else can be done by KIMAI itself..

**Comment by infeeeee** [comment] 2019-12-08 14:52
Kind of duplicate of #571 

There is an android client, maybe the dialog is better there, I never tried it: https://www.kimai.org/store/hmr-it-android-offline-tracker.html

Also kimai is a webapp, native android libraries cannot be used here.

**Comment by kevinpapst** [comment] 2021-03-13 19:58
Closing, as duplicate of #571

**Closed by kevinpapst** 2021-03-13 19:58 UTC
Labels: duplicate
