### ISSUE TITLE
HTTP 500 upon PDF export Windows

### ISSUE THREAD

**Issue by Elijha** [kevinpapst/kimai2#979] opened 2019-07-23 05:30 UTC
I have just setup Kimai for evaluation. After creating a couple of companies, and assigning tasks projects and time without issue I went to export and test the options. I'm fairly certain the last one I clicked was PDF and I now get a server 500 error. even from a different machine on the network that has not accessed it before (ie no browser cache issues).

**Screenshots**
Blank screen. Error (500) on any URL no returned content
ie project.test or project.test/en/homepage

Desktop (please complete the following information):

OS: Windows 2008r2
Browser: Any / Crome
Database: Mysql 5.6.72 64bt

in the log: kimai2-1.0.1\var\log
```
[]
[2019-07-23 12:53:27] php.WARNING: Notice: tempnam(): file created in the system's temporary directory {"exception":"[object] (ErrorException(code: 0): Notice: tempnam(): file created in the system's temporary directory at C:\\Websites\\kimai2-1.0.1\\src\\Export\\Renderer\\OdsRenderer.php:41)"} []
[2019-07-23 12:53:27] request.CRITICAL: Uncaught PHP Exception Exception: "Could not open temporary file" at C:\Websites\\kimai2-1.0.1\src\Export\Renderer\OdsRenderer.php line 43 {"exception":"[object] (Exception(code: 0): Could not open temporary file at C:\\Websites\\kimai2-1.0.1\\src\\Export\\Renderer\\OdsRenderer.php:43)"} []
[2019-07-23 12:53:27] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []

```
**Additional context**

so I guess it went to write to temp and was not able to so now dies a complete death?  I checked the permissions and I had essentially given full inherited access to the IIS_users to the whole Kimai folder so I don't see why it could not write here. I also checked the default PHP.inii setting which point temp to c:windows\temp  - which also has write /read permissions here.

Interestingly. During setup I did try and get the LDAP auth working.. but gave up and created a local admin account and logged in with this.

To try and solve this issue I did try to do a  **bin/console cache:clear**  but this also  errors in the command line with:
```
c:\Websites\kimai2-1.0.1\bin>php console cache:clear

In FileLoader.php line 166:

  The file "C:\Websites\kimai2-1.0.1\config\packages/local.yaml" d
  t contain valid YAML: Indentation problem at line 135 (near "   regis
  n: false") in C:\Websites\kimai2-1.0.1\config\packages/local.yam
  ch is loaded in resource "C:\Websites\kimai2-1.0.1\config\packag
  al.yaml").


In YamlFileLoader.php line 633:

  The file "C:\Websites\kimai2-1.0.1\config\packages/local.yaml" d
  t contain valid YAML: Indentation problem at line 135 (near "   regis
  n: false").


In Parser.php line 592:

  Indentation problem at line 135 (near "   registration: false").
```

**Comment by kevinpapst** [comment] 2019-07-23 11:49
Hi!

> was not able to so now dies a complete death

Yes, thats very likely Kimais self-destruction code, just because I enjoy getting support questions so much LOL

Oh wait: 
>   The file "C:\Websites\kimai2-1.0.1\config\packages/local.yaml" does
  nott contain valid YAML: Indentation problem at line 135 (near "   regis
  n: false").

... maybe its your custom config that causes the problem?
If you clear the cache and then open Kimai with a broken config, it will not work, as it depends on the runtime cache.

Fix your config, clear the cache and everything will work again.

Regarding PDF: 
there was an error that caused the PDF to try to write a temp file in the vendor/ directory. 
Its fixed in master. 

And I do NOT support IIS and Windows.

**Comment by Elijha** [comment] 2019-07-24 02:35
And I do NOT support IIS and Windows.
> Thats OK I don't judge :)

Thank you for your prompt reply and patch I now have a working version again :)

I'm new to the (I'm assuming its this) Symphony way and caching. So the cause and effect of the server not running after trying to generate a PDF did not direct me to the yaml file issue being the issue with it not running as it had not been modified immediately prior to failure. I had initially been trying to get LDAP auth working with no success .. I now realise I needed to rebuild the cache when the local.yaml is modified and therefore my changes were not being used nor causing issue until I tried to get the site going again after the PDF crash. If I didn't try and do so from a command line I would not have had that error to post here as it didn't seem to log it anywhere, and the last log was the file access.

**Comment by kevinpapst** [comment] 2019-07-24 13:12
Happy to see that it works again!
And good to know that Kimai works on IIS as well.

If you encounter any more problems please let me know. I can't support IIS if it is runtime environment problems because I have zero knowledge in the MS admin world. 
But if it is Kimai related I can help.

Was there anything special during installation that was different from the installation docs? Then I could add installation noted for IIS users.

**Comment by Elijha** [comment] 2019-07-25 04:56
(The building/package managing, MYSQL setup and config as per your steps).
Nothing really different from getting any PHP based site running under IIS.
- have PHP installed (web platform installer)
- add the new site binding your domain and setting the root folder to be the /pub directory
- set the Application Pool to unmanaged code (as its not .net)
- give the IIS_USERS read/write permission to the installation folder
- create the URL rewrite rules from the .htaccess file using the in-bulit importer /converter to be in the IIS equivalent web.config file 

Which are all the same steps you would do for say a Wordpress installation.

NOW - some rules using the  %{ENV:BASE}  properties were not able to be converted automatically as IIS did not understand or have a direct equivalent command... but it seems to work with what it did get across (basically pushing everything to index.php). 

I did go looking for another example as I had thought this was essentially a setting from the symphony platform but the examples I saw from people running this under IIS were not like the original .htaccess here - so I'm probably looking up the wrong path. But as I said the routing seems to all be working so I'm not currently too fussed about it (until some AJAX action fails I guess).

**Comment by kevinpapst** [comment] 2019-07-25 14:37
I found this link, even though its for Symfons 3.4 and not 4.x it looks quite the same:
https://symfony.com/doc/3.4/deployment/azure-website.html#configure-the-web-server

I will add a link in the documentation to this issue. Thanks for sharing!

**Comment by kevinpapst** [comment] 2019-07-25 14:41
Closing, as the issue is resolved

**Closed by kevinpapst** 2019-07-25 14:41 UTC
Labels: installation, question
