### ISSUE TITLE
Backup yunoHost Kimai 0.7 to Ubuntu 1.8

### ISSUE THREAD

**Issue by Andrevg09** [kevinpapst/kimai2#1513] opened 2020-03-02 14:19 UTC
Hello Kevin, we have a Kimai version 0.7 on a YunoHost, this one only goes up to version 0.81 and now we want to move to the new version 1.8 on an Ubuntu. Since the database is quite different, the question would be if and how it is possible to take the existing entries with us to the new environment. I hope you can help us, thank you very much. Andre

**Comment by kevinpapst** [comment] 2020-03-02 14:29
In theory it is possible. In practice your are one year and more then 10 releases behind.
I don't think that anyone ever tried such an upgrade. Not that I know of at least.

You would have to install 0.7 first on your server. Import the data and verify that it works.
Remove local.yaml if you have one, then migrate to 0.8 first and convert the times in your database. 
After that, you could try to upgrade directly to 1.8, but I am not sure about that.
Read this one carefully: https://github.com/kevinpapst/kimai2/blob/master/UPGRADING.md

The problem is, the migration steps aren't documented anymore.
Here is the old version of the upgrading guide, which is at least required for 0.8: 
https://github.com/kimai/www.kimai.org/blob/14ca77d9aae0a2a559ad3533c029ad9932c3d7e3/_documentation/updates.md

**Comment by kevinpapst** [comment] 2020-03-04 23:21
No feedback, closing

**Closed by kevinpapst** 2020-03-04 23:21 UTC
