### ISSUE TITLE
Database filled with zero-items when changing activity on lockdown time entries

### ISSUE THREAD

**Issue by stereo9** [kevinpapst/kimai2#3333] opened 2022-05-31 07:36 UTC
**Describe the bug**
One of my coworkers described the following situation to me, I didn't verify yet that this is completely reproducable.

We are tracking project supplements (change orders) through a global activity "Nachtrag".
One co-worker realized, that 2 weeks back, he didn't mark the activity as "Nachtrag".
He went to weekly sheets to calendar week 20 and changed one line activity from "Ausführungsplanung" to "Nachtrag", although, the time entries are already blocked.

![image](https://user-images.githubusercontent.com/55000172/171117879-f4cdd9c8-a775-43a5-af75-e6c4588fecd2.png)

As you can see in the picture, the last project now is set to "Nachtrag". We have the policy to comment all Nachträge, so he checked the timesheet item list "my times"

which came to be quite messy
![image](https://user-images.githubusercontent.com/55000172/171117678-5d11fc2a-5ba1-4149-b890-412e55fc1ebb.png)

I noticed after investigating a little, that basically kimai filled in the empty project items database with 0:00h values
![image](https://user-images.githubusercontent.com/55000172/171118289-837e4ac5-2211-4ebe-93d8-a310ff476e44.png)
the orange marked zeros are now also entries in the db

**Logfile**
```
No new items
```

**Additional context**
 - Kimai version: 1.19.7
 - PHP version: 8.0.16

**Comment by kevinpapst** [comment] 2022-05-31 08:53
Interesting. Maybe some un-common configuration settings that cause this issue.

This function is used by a lot of people every day and I promise (and really hope) that this is not the regular behavior, so please: test in the demo and let me know if you are capable to reproduce it. 
I gave it a try and was not able to reproduce it by either changing project or activity.
If you have the AuditTrail Bundle, please check if these items were created with zero duration or if they were updated multiple times.

I could imagine, that this has to do with your timetracking settings: some combination of the time tracking mode and other time-tracking and rounding related system-configurations.

**Comment by kevinpapst** [comment] 2022-06-19 14:55
Closing due to missing feedback. If you want to share more input, please feel free to comment and re-open.

**Closed by kevinpapst** 2022-06-19 14:55 UTC
Labels: bug, waiting for feedback
