### ISSUE TITLE
invalid generated code in html

### ISSUE THREAD

**Issue by BlackKerio** [kevinpapst/kimai2#2971] opened 2021-11-25 08:13 UTC
**Describe the bug**
 would like to draw your attention to invalid generated code in html.  For example on timesheet and quick_entry page.
1. form inside another html form
2. < is "&lt ;" and > is "&gt ;")

 - Kimai version: 1.16.5
 - PHP version: 7.4.
 - Browser Firefox

**Comment by kevinpapst** [comment] 2021-11-25 08:27
Thanks @BlackKerio 👍 never noticed that. Will be fixed with #2972

**Comment by BlackKerio** [comment] 2021-11-25 09:13
@kevinpapst quick fix ... great. Unfortunately the javascript that generates the data on the quick_entry page also causes a few errors. 
It inserts 'div' directly into the 'tbody' without inserting it into 'tr' I recommend to check the source code also in firefox for example, it highlights in red any errors

**Comment by kevinpapst** [comment] 2021-11-25 10:34
Where/How do you see a `div`? I cannot reproduce that on Safari and Firefox.
But I found another issue with missing CSS classes, so I changed the generation code a bit. 
Can you re-test if you still see the div?

**Comment by BlackKerio** [comment] 2021-11-25 11:57
@kevinpapst 

I am trying the program with an empty database and only one user
browsing in firefox on windows, right button 'code source'

in the template quick-entry/index.html.twig 
form_rest(form) is inserted once at the beginning of the block 'quick_entry_week_row' from the template kimai-theme.html.twig wrong, without '<tr> ..' and then again right with '<tr>'

And before the end of 'tbody' two '< /div >' one < input type="hidden" ...


[Kimai – Suivi du temps.zip](https://github.com/kevinpapst/kimai2/files/7602735/Kimai.Suivi.du.temps.zip)

**Comment by kevinpapst** [comment] 2021-11-25 12:28
Aha. Now I see it. Actually Firefox hides it here on Mac. The developer console shows only cleaned-up HTML and the source code window never worked for me. But I could spot the problem it in Safari.
Will see if I can fix it. 
But tell me: is there any "real problem" besides hurt developer feelings 😁 ? I mean, it maybe invalid HTML but causes no issues/bugs, right?

**Comment by BlackKerio** [comment] 2021-11-25 12:59
It doesn't cause problems yet, because the smart browser is trying to get it right. It'll certainly slow it down, unnecessarily. In the future, the bug may show up when linking javascript to html. The application should generate the correct html code 😁.

The quick_entry page is certainly important, only if the database doesn't have many entries.
There are about 200 projects in our database. Project Tickets has 10000 entries in activity. To generate a select with 10000 options is long, the html page is 4MB. In case the html is not valid, the page length is longer and loading is even slower.

I would like to thank you for the great work you are doing on this project.

**Comment by kevinpapst** [comment] 2021-11-25 13:24
10000 visible activities? Wow, do you really need that many. The Kimai UI is certainly not prepared for such a scenario.

**Comment by BlackKerio** [comment] 2021-11-25 14:03
If the truth be told, we don't need to. But the Pentaho settings that automatically export data to Kima leave everything visible.  *smile*

**Closed** 2021-11-29 14:49 UTC
Labels: bug
