### ISSUE TITLE
How to filter Dashboard

### ISSUE THREAD

**Issue by limitedAtonement** [kevinpapst/kimai2#2115] opened 2020-11-12 00:24 UTC
**Description**
A clear and concise description of what the problem is.

There is no problem, this is a question. The dashboard shows great information including number of working hours this month, week, etc. I would like certain entries not to be considered when calculating number of working hours on the dashboard. Is this possible?

By the way, where is the best place to get support or ask questions like this? Is there an IRC channel for this project?

**Screenshot**
Add a mockup / screenshot of your idea here

![image](https://user-images.githubusercontent.com/7562490/98879359-590f6a00-2453-11eb-9d0f-2bca70056592.png)

This should say 44:35.

**Additional context**
 - Kimai version: 1.10.2 stable (Ayumi)
 - PHP version: PHP 7.4.9 (cli) (built: Sep  1 2020 02:24:56) ( NTS )
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by kevinpapst** [comment] 2020-12-06 22:57
This is not yet possible. Closing as duplicate of #272

**Closed by kevinpapst** 2020-12-06 22:57 UTC
Labels: support

**Comment by limitedAtonement** [comment] 2020-12-07 13:43
Thank you for pointing me to the pre-existing issue! And in general, thank you for keeping the tickets for this project so tidy and well-triaged!

Is there a better place to ask questions like this?

**Comment by kevinpapst** [comment] 2020-12-07 16:43
Please post your questions here and if I will ever setup some dedicated support channels, I will let you know. Its totally fine to post here.
You have a much higher chance to receive feedback here then anywhere else ;-)

**Comment by kevinpapst** [comment] 2020-12-07 16:45
Oh and btw: you can extend the Dashboard, but ONLY with development know-how.
See https://www.kimai.org/documentation/developers.html#extending-the-dashboard-with-widgets

Building something more configurable is on my roadmap, but so are many other features...

**Comment by limitedAtonement** [comment] 2020-12-08 18:49
Awesome, thanks!

It looks like the reporting capabilities in Kimai are pretty primitive at this point; am I missing anything? For instance, if I want to know how much someone worked last week or the week before, how would I go about that?
