### ISSUE TITLE
Add number to API /api/customers

### ISSUE THREAD

**Issue by felixhopfauf** [kevinpapst/kimai2#2167] opened 2020-12-07 08:57 UTC
**Is your feature request related to a problem? Please describe.**
I created an PHP script to add customers from our CRM System to Kimai.
I used the customer number to check if the customer still exists.
To get the number from kimai i had to call every customer directly by id to get the number, and we have over 3000 customers in out database. To get all informations the script spent over 15 minutes working and the cpu load is very high on the server hosting kimai

**Describe the solution you'd like**
Adding the number attribute to the api request /api/customers

**Describe alternatives you've considered**
As discribed above

**Screenshot**
No Screenshot available

**Comment by kevinpapst** [comment] 2020-12-07 16:50
Quick fix for you, replace:
`@Serializer\Groups({"Customer_Entity"})` with `@Serializer\Groups({"Default"})` and refresh the cache.

The problem is that every exposed field is visible to any user of Kimai. And these fields could contain sensitive data, so I am not keen on exposing every field that someone wants to use. The customer number indeed seems to be a legit use-case.

If you want to sent a PR with adapted test cases, don't hesitate to sent one.

**Comment by felixhopfauf** [comment] 2020-12-08 13:02
Hello Kevin,

thanks for quick reply.
I guess that these quick fix will be undone on an update ? I am using the docker image.

PR... puh man... Would be my first one ever so I will need some time to do it the right way ;) 
Which test cases do you expect ?

**Comment by kevinpapst** [comment] 2020-12-08 13:46
Yes, obviously an update will remove such a change.

PR: You don't have to. But you work for a company who uses Kimai for their time management. They can pay me to do the work.

If you want to try it: the tests are all in place, you just have to make sure that the fields are checked.
https://github.com/kevinpapst/kimai2/blob/master/tests/API/APIControllerBaseTest.php#L361

**Comment by kevinpapst** [comment] 2020-12-08 13:46
Closing, because I have no plans to add the field myself.

**Closed by kevinpapst** 2020-12-08 13:46 UTC
Labels: API, feature request
