### ISSUE TITLE
Totals in timesheets

### ISSUE THREAD

**Issue by hpeyerl** [kevinpapst/kimai2#1846] opened 2020-07-27 11:49 UTC
It would be nice to have totals at the bottom of a timesheet query.

Weekly, on Fridays, I have to fill in a timesheet for one of my customers using their timesheet app.  So I do a custom-date range query in /en/timesheet.  Then transcribe the entries into my customer's timesheet app.  At the end, I get a total from my customer's timesheet app.  I then manually add up all the entries in Kimai's timesheet to get the total number of hours and compare with what's in the customer timesheet app just to make sure I haven't missed an entry or mis-entered one.  Having a 'Totals' line at the bottom of the Timesheet report would be handy.

I realize I can generate an 'invoice' without exporting the entries but it's just an extra few steps.

This particular customer has a lot of 'activities' so sometimes my Timesheet query has upwards of 20 or 30 different entries per week.   Sometimes my brain has trouble adding those numbers manually. :)

**Comment by kevinpapst** [comment] 2020-07-27 14:51
You can use the invoice screen, it will give you a total in the overview. 
Or you can create/print an invoice preview which will give you the total hours as well.

I am closing this ticket as duplicate of #819, please vote with a 👍 reaction on the initial post there to give the ticket a higher priority.

**Closed by kevinpapst** 2020-07-27 14:51 UTC
Labels: duplicate
