### ISSUE TITLE
Upgrading to new version gives foreign key exception

### ISSUE THREAD

**Issue by jaapcrezee** [kevinpapst/kimai2#1447] opened 2020-02-08 16:49 UTC
**Describe the bug**
Upgrading to new version gives foreign key exception

**Logfile**
```
Using Mysql DB
Wait for db connection ...
Connection established
first run - install kimai

Kimai installation running ...
==============================

Database `kimai` for connection named default already exists. Skipped.
                                                              
                    Application Migrations                    
                                                              

Migrating up to 20200109102138 from 20191116110124

  ++ migrating 20191204120823 (Adds project_start and project_end to projects tables)

     -> ALTER TABLE kimai2_projects ADD start DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', ADD end DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', ADD timezone VARCHAR(64) DEFAULT NULL

  ++ migrated (took 531.4ms, used 16M memory)

  ++ migrating 20200109102138 (Creates comment tables for customers and projects)

     -> DELETE from kimai2_configuration WHERE name = "theme.select_type"
     -> DELETE from kimai2_roles_permissions WHERE permission = "delete_other_profile"
     -> DELETE from kimai2_roles_permissions WHERE permission = "delete_own_profile"
     -> CREATE TABLE kimai2_customers_comments (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, created_by_id INT NOT NULL, message LONGTEXT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime)', pinned TINYINT(1) DEFAULT '0' NOT NULL, INDEX IDX_A5B142D99395C3F3 (customer_id), INDEX IDX_A5B142D9B03A8386 (created_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
     -> CREATE TABLE kimai2_projects_comments (id INT AUTO_INCREMENT NOT NULL, project_id INT NOT NULL, created_by_id INT NOT NULL, message LONGTEXT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime)', pinned TINYINT(1) DEFAULT '0' NOT NULL, INDEX IDX_29A23638166D1F9C (project_id), INDEX IDX_29A23638B03A8386 (created_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
     -> ALTER TABLE kimai2_customers_comments ADD CONSTRAINT FK_A5B142D99395C3F3 FOREIGN KEY (customer_id) REFERENCES kimai2_customers (id) ON DELETE CASCADE
Migration 20200109102138 failed during Execution. Error An exception occurred while executing 'ALTER TABLE kimai2_customers_comments ADD CONSTRAINT FK_A5B142D99395C3F3 FOREIGN KEY (customer_id) REFERENCES kimai2_customers (id) ON DELETE CASCADE':

SQLSTATE[HY000]: General error: 1005 Can't create table `kimai`.`#sql-1_1453ae` (errno: 150 "Foreign key constraint is incorrectly formed")
 [ERROR] Failed to set migration status: An exception occurred while executing  
         'ALTER TABLE kimai2_customers_comments ADD CONSTRAINT                  
         FK_A5B142D99395C3F3 FOREIGN KEY (customer_id) REFERENCES               
         kimai2_customers (id) ON DELETE CASCADE':                              
                                                                                
         SQLSTATE[HY000]: General error: 1005 Can't create table                
         `kimai`.`#sql-1_1453ae` (errno: 150 "Foreign key constraint is         
         incorrectly formed")                                                   

Kimai2 ready
```

Could be related:
```
www-data@68a0a207117c:/opt/kimai$ ./bin/console kimai:update

Kimai updates running ...
=========================

                                                              
                    Application Migrations                    
                                                              

Migrating up to 20200109102138 from 20191204120823

  ++ migrating 20200109102138 (Creates comment tables for customers and projects)

Migration 20200109102138 failed during Execution. Error The table with name 'kimai.kimai2_customers_comments' already exists.
                                                                                                                        
 [ERROR] Failed to set migration status: The table with name 'kimai.kimai2_customers_comments' already exists.          

```

Running on:
```
        "Id": "sha256:df935724b82f821e2f4c52d51c53b039c232b157e052af2206f4097d44deb2b6",
        "RepoTags": [
            "kimai/kimai2:apache-debian-master-prod"
        ],
        "RepoDigests": [
            "kimai/kimai2@sha256:7408445501bdb1433620d9df1d9f5bc7007cc5ab17bcc6efb6b7723ae55b2002"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2020-01-27T12:11:33.956274455Z",
```

Mariadb: `Server version: 10.2.15-MariaDB-10.2.15+maria~jessie - mariadb.org binary distribution`

```
www-data@68a0a207117c:/opt/kimai$ ./bin/console kimai:version
Kimai 2 - 1.7 stable (Ayumi) by Kevin Papst and contributors.
```

**Comment by jaapcrezee** [comment] 2020-02-08 17:06
And when trying to create new timesheet entries, I get this error now (could well be related to the failed migration):
```
[2020-02-08 17:04:29] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO kimai2_user_preferences (name, value, user_id) VALUES (?, ?, ?)' with params ["theme.layout", "fixed", 1]:  SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value" at /opt/kimai/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO kimai2_user_preferences (name, value, user_id) VALUES (?, ?, ?)' with params [\"theme.layout\", \"fixed\", 1]:\n\nSQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value at /opt/kimai/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value at /opt/kimai/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value at /opt/kimai/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []
```

**Comment by kevinpapst** [comment] 2020-02-08 17:35
>          SQLSTATE[HY000]: General error: 1005 Can't create table                
>         `kimai`.`#sql-1_1453ae` (errno: 150 "Foreign key constraint is         
>        incorrectly formed")                                                   

As you can see from the statements, Kimai didn't try to create such a table. 
Might be docker related, who knows...
Please ask in the docker repo, if anyone has an idea.

**Comment by jaapcrezee** [comment] 2020-02-08 17:44
I do not see why this could be container-related; to me, it just seems as kimai2 v 1.7 is just unable to reliably perform this migration: Migrating up to 20200109102138 from 20191204120823

**Comment by kevinpapst** [comment] 2020-02-08 17:50
I do not see why this could be Kimai-related; the update worked fine for many users in classical hosting environments. Additional the migrations are running in Travis with every commit, so they are pretty well tested.

But please have look and tell me where this broken SQL is coming from, I can't see it:
https://github.com/kevinpapst/kimai2/blob/master/src/Migrations/Version20200109102138.php

I will not invest time in debugging something I am 100% sure that it is working, as I executed the update already in a lot of environments of my own customers => where no one is using docker, so this is the only quick guess I can give you. 
You can clone 1.6, install it and the immediately migrate up to 1.7. If you run into the same problem, I will have a look.

**Comment by jaapcrezee** [comment] 2020-02-08 17:59
Okay thank you, I will have a look.

/ offtopic:
I am .01 milliseconds away from ditching the Kimai docker container(s) because this is one of many problems after upgrading [ I am using a lot of docker containers and never have similar problems with other containers like wordpress, mysql, gitlab, owncloud, phpmyadmin etc ].
Although for now I am unsure what the best alternative would be given the requirement that the kimai2 application should run in a docker container and be exposed by a http server running in the same container so the host nginx instance can proxy it from a https interface.

**Comment by kevinpapst** [comment] 2020-02-08 18:04
I totally do understand the frustration, but ... 

> wordpress, mysql, gitlab, owncloud, phpmyadmin

... please don't compare apples with oranges. Kimai is a one person project (with a growing community, but still) and the docker containers are provided by two great guys from that community. 

You can hardly compare some of the biggest available open source projects in the world, which are btw all backed by huge companies, with a project like Kimai (even though, I tend to say "thanks" for naming it in one sentence with them).

If you have the knowledge to make it better: please go ahead and bring in your knowledge and ideas!

**Comment by jaapcrezee** [comment] 2020-02-08 18:12
You are welcome, and because you always respond quite quickly I have not moved to something else.
And by the way, rest assured that "huge company" is of insignificant value to me given that I have even more problems with Azure integrations.
If I can get kimai working again for me soon, I will make sure you get another donation ;).

**Comment by kevinpapst** [comment] 2020-02-08 18:18
BTW: After reading a bit the error message could happen in cases when the two linked columns are:
- not of the same type
- not of the same length
- not of the same character set

So maybe this is somehow related to the used MariaDB version and its default configuration.
I have seen more than enough strange database bugs ... so maybe this is one of these times where just a handful of all users are affected.

Can you show me the output of `show create table kimai2_customers;`

**Comment by jaapcrezee** [comment] 2020-02-08 18:21
```
172.17.0.1/kimai/kimai2_configuration/		https://<removed>/tbl_sql.php?db=kimai&table=kimai2_configuration
Your SQL query has been executed successfully.

show create table kimai2_customers



kimai2_customers	CREATE TABLE `kimai2_customers` (
  `id` int(11) NOT NULL,
  `name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `number` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comment` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `visible` tinyint(1) NOT NULL,
  `company` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country` varchar(2) COLLATE utf8mb4_unicode_ci NOT NULL,
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fax` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mobile` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `homepage` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `timezone` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fixed_rate` double DEFAULT NULL,
  `hourly_rate` double DEFAULT NULL,
  `color` varchar(7) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `time_budget` int(11) NOT NULL DEFAULT 0,
  `budget` double NOT NULL DEFAULT 0,
  `vat_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci	
```

**Comment by kevinpapst** [comment] 2020-02-08 18:22
And the same for `kimai2_customers_comments`?

**Comment by kevinpapst** [comment] 2020-02-08 18:23
And `describe kimai2_customers;` + `describe kimai2_customers_comments;`  just to make sure we don't miss anything...

**Comment by jaapcrezee** [comment] 2020-02-08 18:35
> kimai2_customers_comments

```
kimai2_customers_comments	CREATE TABLE `kimai2_customers_comments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_id` int(11) NOT NULL,
  `created_by_id` int(11) NOT NULL,
  `message` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL COMMENT '(DC2Type:datetime)',
  `pinned` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `IDX_A5B142D99395C3F3` (`customer_id`),
  KEY `IDX_A5B142D9B03A8386` (`created_by_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci	
```

```
MariaDB [kimai]> describe kimai2_customers;
+-------------+--------------+------+-----+---------+-------+
| Field       | Type         | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+-------+
| id          | int(11)      | NO   |     | NULL    |       |
| name        | varchar(150) | NO   |     | NULL    |       |
| number      | varchar(50)  | YES  |     | NULL    |       |
| comment     | text         | YES  |     | NULL    |       |
| visible     | tinyint(1)   | NO   |     | NULL    |       |
| company     | varchar(255) | YES  |     | NULL    |       |
| contact     | varchar(255) | YES  |     | NULL    |       |
| address     | text         | YES  |     | NULL    |       |
| country     | varchar(2)   | NO   |     | NULL    |       |
| currency    | varchar(3)   | NO   |     | NULL    |       |
| phone       | varchar(255) | YES  |     | NULL    |       |
| fax         | varchar(255) | YES  |     | NULL    |       |
| mobile      | varchar(255) | YES  |     | NULL    |       |
| email       | varchar(255) | YES  |     | NULL    |       |
| homepage    | varchar(255) | YES  |     | NULL    |       |
| timezone    | varchar(64)  | NO   |     | NULL    |       |
| fixed_rate  | double       | YES  |     | NULL    |       |
| hourly_rate | double       | YES  |     | NULL    |       |
| color       | varchar(7)   | YES  |     | NULL    |       |
| time_budget | int(11)      | NO   |     | 0       |       |
| budget      | double       | NO   |     | 0       |       |
| vat_id      | varchar(50)  | YES  |     | NULL    |       |
+-------------+--------------+------+-----+---------+-------+
22 rows in set (0.00 sec)

MariaDB [kimai]> describe kimai2_customers_comments;
+---------------+------------+------+-----+---------+----------------+
| Field         | Type       | Null | Key | Default | Extra          |
+---------------+------------+------+-----+---------+----------------+
| id            | int(11)    | NO   | PRI | NULL    | auto_increment |
| customer_id   | int(11)    | NO   | MUL | NULL    |                |
| created_by_id | int(11)    | NO   | MUL | NULL    |                |
| message       | longtext   | NO   |     | NULL    |                |
| created_at    | datetime   | NO   |     | NULL    |                |
| pinned        | tinyint(1) | NO   |     | 0       |                |
+---------------+------------+------+-----+---------+----------------+
6 rows in set (0.00 sec)

```

**Comment by kevinpapst** [comment] 2020-02-08 18:39
Ok, the problem is your database, but I don't understand it.
The customers table ID definition is wrong. 
It must look the same like in the comments table. 
Can you even create customers, if there is no auto-increment value set?

**Comment by jaapcrezee** [comment] 2020-02-08 18:41
As of now: no.
Before the upgrade? For sure, or else I would be out of business.
Could this be related to the fact that I came all the way from kimai1 (which might not be the case for other instances of Kimai2 elsewhere)?

**Comment by kevinpapst** [comment] 2020-02-08 18:45
No, I am running multiple customers which I migrated up from Kimai 1.
But I remember that you started quite early with Kimai 2, so maybe some older migration caused that.

Let try to fix it... first of all delete the new tables `DROP TABLE kimai2_customers_comments;` & `DROP TABLE kimai2_projects_comments;`

Then fix the customers table by adding "auto increment" & "primary key" to the customers table.
Afterwards you should be able to execute the migration.

**Comment by jaapcrezee** [comment] 2020-02-08 18:46
Okay, I will try that.

**Comment by kevinpapst** [comment] 2020-02-08 18:47
And add the index `IDX_5A9760447AB0E859` to the `visible` column of the customer table. The  index name is important, as it might be referenced in some coming migrations.

**Comment by jaapcrezee** [comment] 2020-02-08 19:13
Okay I found it. It is not related to Kimai itself, so you were 100% right from the beginnen (good gut feeling!).

The problem arose from two main problem areas:

- For my first installation, I was running from the `kimai/kimai2:prod` container. This container is no longer available and by accident, I ran `kimai/kimai2:latest` once (instead of `kimai/kimai2:apache-debian-master-prod`) and found out kimai was not working any longer so I dropped the database tables and started over (import backup)
- That import failed but I neglected to dive into the details. My database contained a few views which I created manually. Those views failed to (re)import and the remaining databases indexes where no longer restored.

After removing the offending views from the SQL dump and reimporting it without errors the kimai migration worked flawlessly.

Please excuse me for my bad not-reading-so-well behavior and accept my apologies backed by the the following punishment duties (write down the following sentence 100 times on the blackboard)

"I failed to follow good engineering practices and by that I burned somebody elses time. Next time I will be more careful. I failed to follow good engineering practices and by that I burned somebody elses time. Next time I will be more careful. I failed to follow good engineering practices and by that I burned somebody elses time. Next time I will be more careful.  .... "

**Comment by kevinpapst** [comment] 2020-02-08 19:19
😁 and thanks for PP!

But does that mean there are more indexes missing?

**Comment by jaapcrezee** [comment] 2020-02-08 19:21
Not anyway after reimporting; I only miss my own views now which I recognize should be able to be created again manually, but for now, I do not bother.

**Comment by kevinpapst** [comment] 2020-02-08 19:26
And the update worked properly this time?

**Comment by jaapcrezee** [comment] 2020-02-08 19:33
The update worked properly this time.

WRT running kimai from a production container:

The page https://www.kimai.org/documentation/docker.html#production-docker points to the link https://github.com/tobybatch/kimai2 .
The documentation found on that page only mentions the production container using docker compose. I do not want to use compose for running kimai in my production environment; I only want one self-contained container exposing kimai using a http server running in the container and with kimai using a pre-existing mysql/mariadb server.
This is how I currently use it:

```
#!/bin/sh

IMAGE=kimai/kimai2:apache-debian-master-prod

docker run --restart always -d \
    -p 127.0.0.1:<host-port-on-your-docker-machine>:8001 \
    --name kimai \
    -e MAILER_FROM=<your-from-email-address> \
    -e APP_ENV=prod \
    -e APP_SECRET=<fill-in-your-secret-here> \
    -e DATABASE_URL=mysql://<mysql-username>:<mysql-password>@<mysql-database-ip>/<mysql-database-name> \
    -e MAILER_URL=smtp://<smtp-server-ip>:<smtp-server-port> \
    --volume <the-var-folder-on-your-host>:/opt/kimai/var \
    --volume <the-invoice-folder-on-your-host>:/opt/kimai/var/invoices \
    --volume <your-timezone-file>:/etc/localtime \
    $IMAGE
```

The following line could probably be removed, but I keep it for historical purposes.

```
    --volume <the-invoice-folder-on-your-host>:/opt/kimai/var/invoices \
```

I also had to create some directories in the /opt/kimai/var folder:
`data` and `plugins`

The same host on which the docker daemon runs proxies https://<some-domain> to 127.0.0.1:<host-port-on-your-docker-machine> using nginx.

**Comment by kevinpapst** [comment] 2020-02-08 20:05
Sounds like a good idea. 
I hope users who host docker know how to handle it. I don't want to add too much about docker to the Kimai docs, as I cannot really support it (not enough knowledge).
As your problem is solved, I am closing here.

**Closed by kevinpapst** 2020-02-08 20:05 UTC
Labels: docker, question
